### ISSUE TITLE
Hooks to add custom tutorial videos and custom controls

### ISSUE THREAD

**Issue by xxtesaxx** [elegantthemes/create-divi-extension#10]
Is there any intention to let us add video tutorials via hooks or is there a best practice to add support content to our modules? A while ago I played with the ability to add custom tabs to my modules and create a custom control to only display some html - which brings me to the next question: how to add custom controls? I know how to hack something together to add custom controls to the backend builder but I'm not sure that this will work on the VB so are there any best practices as well?

**Comment by lots0logs** [comment]
>Is there any intention to let us add video tutorials via hooks or is there a best practice to add support content to our modules? 

As a matter of fact there is :wink: 

https://github.com/elegantthemes/divi-extension-example/blob/8837a49901b81c410fdad56f067c0523250d0e8e/includes/modules/CustomCtaAllOptions/CustomCtaAllOptions.php#L133-L140

> while ago I played with the ability to add custom tabs to my modules and create a custom control to only display some html - which brings me to the next question: how to add custom controls? 

Support for custom tabs is already available. Support for custom controls will be coming in a future release. You can see an example of a custom tab implementation here: 

https://github.com/elegantthemes/divi-extension-example/blob/master/includes/modules/CustomCtaAllOptions/CustomCtaAllOptions.php#L35-L42

**Comment by xxtesaxx** [comment]
Awesome! Thanks a lot. :) One final question for today: how about a slack channel for developer exchange?

**Comment by lots0logs** [comment]
Unfortunately, I can neither confirm nor deny that a Slack Channel is in the works lol :wink:
