### ISSUE TITLE
Insert cropped image

### ISSUE THREAD

**Issue by ghost** [elegantthemes/create-divi-extension#123]
Does a problem of choosing a size of an image to insert in modules have a solution?
Natively in WP, we can choose one of the available sizes. It's not the case for Divi's modules.

![2018-06-24_194525](https://user-images.githubusercontent.com/11320080/41821628-67a96982-77ec-11e8-9062-e667a745f5b4.jpg)
The lack of this feature affects the performance of the site, especially for mobile users with additional bandwidth used.

**Comment by web2033** [comment]
@xxtesaxx Did you make it as a custom/modified module or some custom code that works for all places where there's an image field?

I was mentioning alt/srcset too here
https://github.com/elegantthemes/create-divi-extension/issues/117

**Comment by xxtesaxx** [comment]
For the title and alt attributes I use Wordpress functions to check If the
URL from the field belongs to an attachment And then load the title and alt
from the attachment

Eugene Kopich <notifications@github.com> schrieb am Mo. 9. Juli 2018 um
11:58:
