### ISSUE TITLE
yarn start - Unable to locate wp-config.php! (Multisite)

### ISSUE THREAD

**Issue by web2033** [elegantthemes/create-divi-extension#13]
I'm trying to get started using WordPress Multisite installation and see this error:

![2018-04-22_000954](https://user-images.githubusercontent.com/11320080/39088851-780662fa-45c2-11e8-9581-963a5425e07d.jpg)

Is this tool compatible with Multisite?

**Comment by lots0logs** [comment]
The tool expects there to be a `wp-config.php` file somewhere higher up in plugin's path. Where is your `wp-config.php` file located?

**Comment by lots0logs** [comment]
Okay, could you post here the complete path of your plugins directory (you can change any parts of the path that are unique to your system to something fictitious)

**Comment by web2033** [comment]
It can be seen on the very first screenshot:
`E:\wamp64\www\divi.test\ms\wp-content\plugins`

**Comment by lots0logs** [comment]
Okay, basically what it does is looks for the wp-config file in these directories and in this order:

* E:\wamp64\www\divi.test\ms\wp-content
* E:\wamp64\www\divi.test\ms
* E:\wamp64\www\divi.test
* E:\wamp64\www
* E:\wamp64

If your config is located in one of those directories it should find it. Please let me know. Thanks.

**Comment by lots0logs** [comment]
This could have something to do with Windows-style paths vs Unix-style paths. I'll look into it. Unfortunately there isn't an easy work-around in the meantime since I do not yet know what is causing the issue for you. Sorry!

**Comment by web2033** [comment]
Additionally, I've installed **local flywheel**, but I see the same error after
`yarn start`

It runs after
`npm start`
with some errors in console:
![2018-04-22_121726](https://user-images.githubusercontent.com/11320080/39093484-134d59b0-4629-11e8-8d1b-e5e73e7d3295.jpg)

**Comment by lots0logs** [comment]
That is a known issue with Local By Flywheel..there is a [work-around](https://github.com/elegantthemes/create-divi-extension/issues/5#issuecomment-383213326) for it though.

**Comment by Hermitzan** [comment]
![image](https://user-images.githubusercontent.com/48967226/80224467-5829fe80-860f-11ea-87a2-70417de50a5f.png)

**Comment by Hermitzan** [comment]
> 
> 
> I'm trying to get started using WordPress Multisite installation and see this error:
> 
> ![2018-04-22_000954](https://user-images.githubusercontent.com/11320080/39088851-780662fa-45c2-11e8-9581-963a5425e07d.jpg)
> 
> Is this tool compatible with Multisite?

@web2033 I resolve that as follow
On file \divi-dev-utils\WPConfig.js constructor() change the order of `const cwd` value from `process.env.PWD || process.cwd()` to `process.cwd() || process.env.PWD`. It is because `process.cwd()` returns the correct path for Windows.

**Comment by web2033** [comment]
@Hermitzan Thanks. 
Maybe someone will need it. I moved on to Vue.js 😉
