### ISSUE TITLE
Module not found: You attempted to import ../../../../../../../wp-admin/images/wpspin_light-2x.gif which falls outside of the project src/ directory

### ISSUE THREAD

**Issue by xxtesaxx** [elegantthemes/create-divi-extension#15]
I want to use Freemius (freemius.com) to sell my plugin and the SDK contains a CSS file under /assets/css/admin/common.css which contains this property:

    background:url("../../../../../../../wp-admin/images/wpspin_light-2x.gif");

When I try to run `yarn start` I get the following error message:

    Failed to compile.    
    ./includes/freemius/assets/css/admin/common.css
    Module not found: You attempted to import ../../../../../../../wp-admin/images/wpspin_light-2x.gif which falls outside of the project src/ directory. Relative imports outside of src/ are not supported. You can either move it inside src/, or add a symlink to it from project's node_modules/.

I placed the Freemius SDK under my-extension/includes/freemius.

**Comment by web2033** [comment]
The idea is to offer a free plugin and then to sell premium features (extended version)?

**Comment by xxtesaxx** [comment]
I moved the whole SDK out of the includes folder into the top level and that seemed to fix the error when running yarn
