### ISSUE TITLE
How we can remove background setting in my custom module?

### ISSUE THREAD

**Issue by sharazghouri** [elegantthemes/create-divi-extension#152]
### Problem Description
How can we remove the background setting in my custom module?

### Steps To Reproduce
1.
![image](https://user-images.githubusercontent.com/17900945/44190059-296f3b80-a13e-11e8-8271-72b524b0d320.png)

**Comment by SatishKumarPrajapati** [comment]
You can remove background by advanced filed config
$advanced_fields['background']      = false;

use this code to disable background.

**Comment by sharazghouri** [comment]
Thanks

**Comment by sharazghouri** [comment]
@SatishKumarPrajapati  if we want to remove any sub toggle in the background like background image or background video.

**Comment by lots0logs** [comment]
@sharazghouri Check out the first parapgraph [here](https://www.elegantthemes.com/documentation/developers/divi-module/advanced-field-types-for-module-settings/).
