### ISSUE TITLE
Page Builder :: Custom Module :: Fields display dependencies not working in child item modal

### ISSUE THREAD

**Issue by ulkoalex** [elegantthemes/create-divi-extension#159]
### Problem Description
Display dependencies for fields not working in child element.

In `et_pb_init_main_settings` function there's:

`var module_type = $container.data( 'module_type' );`

But for child element modal there's no `data-module_type` attribute:
For default module modal in `ET_PageBuilder.ModalView.render` there's:
```
view_settings['attributes'] = {
	'data-module_type' : this_module_type
};
```
But for child element it's missing, in `ET_PageBuilder.AdvancedModuleSettingView.showSettings` there's:

```
view = new ET_PageBuilder.AdvancedModuleSettingEditViewContainer( {
	view : this,
	attributes : {
		show_settings_clicked : ( event ? true : false )
	}
} );
```
So `data-module_type` is missing in `attributes `, so `module_type` will be empty, and display dependencies will be never initialized:
`if ( has( window.et_pb_module_field_dependencies, module_type ) ) {`
With empty `module_type` this condition won't be passed.

### Steps To Reproduce

1. Create Custom Module
```
class My_Module extends ET_Builder_Module {
	public $slug  = 'et_pb_my_module';
	public $child_slug = 'et_pb_my_module_child';
	...
```

2. Create child element
```
class My_Module_Child extends ET_Builder_Module {
	public $slug  = 'et_pb_my_module_child';
	public $type  = 'child';
```

3. Add control field (in child element)
```
'my_select_field' => [
	'type'        => 'select',
	'label'       => 'My Select',
	'options'     => [
		'option_1'  => 'Option 1',
		'option_2'  => 'Option 2',
	]
]
```

4. Add filed with display dependency (in child element)
```
 'my_text_field' => [
	'type'        => 'text',
	'label'       => 'My text',
	'show_if'   => [
		'my_select_field' => 'option_1'
	]
]
```

5. Add child element, in opened modal display dependency doesn't work (`my_text_field` field is always hidden)

### Screenshot and/or gif

![child_item](https://user-images.githubusercontent.com/2953785/44432308-39f23c80-a5aa-11e8-937b-554d3964786a.png)

![child_data-module_type_missing](https://user-images.githubusercontent.com/2953785/44432197-b5072300-a5a9-11e8-885d-6cf2645582c4.png)

**Comment by lots0logs** [comment]
This is already being tracked on an issue in Divi's repo (elegantthemes/Divi#10828). We'll have it fixed in the New Backend Builder Experience release coming in 2 weeks.
