### ISSUE TITLE
How to hide the new advanced/Divi built-in fields?

### ISSUE THREAD

**Issue by jcdotnet** [elegantthemes/create-divi-extension#166]
### Problem Description
Hi, all we know thanks to the Divi API we can hide some advanced fields but there are currently new advanced / fuilt-in fields that we might want to hide but we don't have the API / documentation updated, so we need some support in this regard.

For example, **we might want not to use the new automatically added `Link` group.**

**We might also want not to use the new hover feature**, is there any way to disable it? Let's imagine we want to hide the hover selector in the background advanced field. How could we do that?

----
In my original post I was trying to hide a field (`animation-repeat`) from the animation advanced field with no success.

### Steps To Reproduce
1. Hide unwanted advanced fields / fields in advanced fields

**Comment by themohdarif** [comment]
@jcdotnet Kindly refer #198

**Comment by themohdarif** [comment]
In the same manner, you can control all the other features. You can overwrite unwanted features in your module file or can modify them by returning desired output.

**Comment by jcdotnet** [comment]
Thank you @themohdarif  

Worked and I have overrided some other features too,  but I can't hide the hover option in the background field yet, any ideas?

![hide_hover_option](https://user-images.githubusercontent.com/10810636/50350994-197ac480-0541-11e9-95e7-3859e5f4ce2b.png)

Thanks in advance!
