### ISSUE TITLE
Removing border_radii in custom child module

### ISSUE THREAD

**Issue by RuuddM** [elegantthemes/create-divi-extension#173]
### Problem Description
I'm making a module which needs to have a option for border styling, so I used the advanced border field. However I don't want to give the user a option to define a border radius. Is there a way to disable this option, like the use_background_image for example? I couldn't find this option myself.

If there is no such option I would recreate the border styling myself. But I can't seem to use icons from the border styles tab. Like this example from Border.php file for example 'icon' => 'border-top'. Now I know that some icons in tabbed subtoggles need this line of code: 'bb_icons_support' => true. This however does not seem to work for the border icons. If someone knows more about this it would be much appreciated. 

Also I'm working in a child-module.

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/31505717/46135862-80d8ef00-c246-11e8-94db-457d49b6ffd2.png)

**Comment by RuuddM** [comment]
It also looks like $this->advanced_fields = array('border') in the child module takes the parameters of its parent module as default, even if there is a default defined.

**Comment by xxtesaxx** [comment]
I believe there is currently no setting to disable parts of the border settings as it is possible with other settings. You could however simply build your own composite setting to only show a color field, a width range slider and the type of the border

**Comment by RuuddM** [comment]
Thanks for the reaction. And I already did.
