### ISSUE TITLE
Text Field (tiny mce) not showing on backend

### ISSUE THREAD

**Issue by snewsh** [elegantthemes/create-divi-extension#176]
**Problem Description**
I have used the create-divi-extension without any changes to the code and the module is working on the front end VB but only the Background and Admin label sections are available on the backend.
The same issue is showing in Chrome, Firefox and Safari and two different local servers (Local by Flywheel and Mamp)

**Things I've Tried**
Clearing Caches/Local Storage
Re-Installing dependancies (Yarn and Node)
Re-Installing local servers
Everything is up to date

**Screenshots**
Front End (All Good)
![screen shot 2018-10-02 at 13 23 19](https://user-images.githubusercontent.com/43791070/46364751-9e56f000-c66e-11e8-961a-97b0cd2042f3.png)

Back End (Not so Good)
![screen shot 2018-10-02 at 13 21 14](https://user-images.githubusercontent.com/43791070/46364760-a2830d80-c66e-11e8-9a12-cf1b83fb9f0b.png)

Hope someone can help. it's driving me mad!
Thank you.

**Comment by xxtesaxx** [comment]
In which settings toggle have you put the field? If its the default main_content toggle, that could probably the issue if you don't setup that toggle yourself. Instead create your own toggle and put it inside it. Or use "text" as the toggle, which should also work I believe

**Comment by xxtesaxx** [comment]
Have you cleared the localStorage? The BB caches the settings so when you change something you have to call window.localStorage.clear() on the JS console of your browser.

Ideally you add your own toggles and put the field in there. You can create toggles in init() like so:


```
$this->settings_modal_toggles = [
--
'general' => [
'toggles' => [
// 'title' => esc_html__('Title', 'ds-suit'),
// 'content' => esc_html__('Content', 'ds-suit'),
'text' => esc_html__('Text', 'ds-suit'),
'link' => esc_html__('Link', 'ds-suit'),
'image' => esc_html__('Image', 'ds-suit'),
],
],
'advanced' => [
'toggles' => [
'text' => [
'title' => esc_html__('Text', 'ds-suit'),
'priority' => 49,
'tabbed_subtoggles' => true,
'sub_toggles' => [
'header' => array(
'name' => esc_html__('Header', 'ds-suit'),
),
'body' => array(
'name' => esc_html__('Body', 'ds-suit'),
),
],
],
// 'image' => esc_html__( 'Image', 'ds-suit' ),
// 'size' => esc_html__( 'Size', 'ds-suit' ),
],
],
];


$this->settings_modal_toggles = [
--
'general' => [
'toggles' => [
// 'title' => esc_html__('Title', 'ds-suit'),
// 'content' => esc_html__('Content', 'ds-suit'),
'text' => esc_html__('Text', 'ds-suit'),
'link' => esc_html__('Link', 'ds-suit'),
'image' => esc_html__('Image', 'ds-suit'),
],
],
'advanced' => [
'toggles' => [
'text' => [
'title' => esc_html__('Text', 'ds-suit'),
'priority' => 49,
'tabbed_subtoggles' => true,
'sub_toggles' => [
'header' => array(
'name' => esc_html__('Header', 'ds-suit'),
),
'body' => array(
'name' => esc_html__('Body', 'ds-suit'),
),
],
],
// 'image' => esc_html__( 'Image', 'ds-suit' ),
// 'size' => esc_html__( 'Size', 'ds-suit' ),
],
],
];


```

**Comment by snewsh** [comment]
Thank you Jan. I had tried localStorage.clear() but that didn't work. Your recommendation of window.localStorage.clear() seems to have done the trick. Thank you very much for the additional information also.

**Comment by mehedi101** [comment]
The same issue on docker for windows also.

**Comment by lots0logs** [comment]
@mehedi101 Please try running `window.localStorage.clear()` in the browser console.
