### ISSUE TITLE
Display logic does not work on child modules

### ISSUE THREAD

**Issue by xxtesaxx** [elegantthemes/create-divi-extension#177]
In child modules, the show_if display logic currently does not work. However, the old depends_on is working so it was probably only forgotten to migrate to the new logic.

**Comment by xxtesaxx** [comment]
Exactly

**Comment by lots0logs** [comment]
This is already being tacked on an issue in Divi's repo (elegantthemes/Divi#10828). We'll have it fixed in the New Backend Builder Experience release coming in 2 weeks.
