### ISSUE TITLE
Bug: Partial VB support module

### ISSUE THREAD

**Issue by bloh2** [elegantthemes/create-divi-extension#178]
### Problem Description
Let's say a sample page has a partial VB support module. When you first load the page in VB, then you simple click any settings, then click close button, then you will see that the partial VB support module will be missing partially / completely.

### Screenshot and/or gif
Here's a video showing the issue: http://recordit.co/Tf3MhXfc9P

I tested using ElegantThemes github sample modules.

**Cause my custom module (partial VB support) is having the same issue. For my custom module, it disappear completely after clicking 'X' for the first time.

The problem only occur when:
When it first load, you click any settings (sections, rows or module), and click close.

If you click tick for the first time, then it works fine afterwards.

**Comment by bitfade** [comment]
This was indirectly fixed by other changes
