### ISSUE TITLE
Lots of error is thrown on yarn start when module has no bundle.js compiled

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/create-divi-extension#182]
### Problem Description
This issue is branched off from the second issue of https://github.com/elegantthemes/create-divi-extension/issues/100:

> If you set a default for the border, the React components render() function is called infinitely which can cause the browser to stop reacting on slower computers.

See the screenshot: https://www.youtube.com/watch?v=Qsw01euRnXI&feature=youtu.be

While working on https://github.com/elegantthemes/create-divi-extension/issues/100, i noticed that the issue only occurs when hot reload bundle is generated via `yarn start` and the module doesn't have bundle.js generated via `yarn build` yet. If the module already have the bundle.js, the error doesn't occur.

The error points to `node_modules/divi-error-overlay/lib/index.js` package. 

### Steps To Reproduce
1. Make sure that there's no bundle js on your `extension/scripts` dir
2. run `yarn start` 
3. Try modifying your custom module

### Screenshot and/or gif
https://www.youtube.com/watch?v=Qsw01euRnXI&feature=youtu.be

![screen shot 2018-10-16 at 16 59 40](https://user-images.githubusercontent.com/916442/47008671-e5f87400-d164-11e8-8fb0-ab2d92a1e9da.png)

**Comment by bitfade** [comment]
This has been fixed by other commits.
