### ISSUE TITLE
Fields get empty after page update

### ISSUE THREAD

**Issue by rosoam** [elegantthemes/create-divi-extension#184]
Hi everyone!

### Problem Description
I'm having an issue with a personnal divi extension - which has child.
( I referred to CustomCtaParent and CustomCtaChild ) folders to create it.

When I fill my fields in the divi builder, everything is okey, BUT once I update the page (with wordpress update button), all the fields of my extension get empty !

Did one of you guys had the same issue?

### Steps To Reproduce
1. Fill the fields 
![screen1](https://user-images.githubusercontent.com/16406319/47085909-662be180-d218-11e8-99e8-fc18d9bf81be.png)

2. Fill the child fields
![screen2](https://user-images.githubusercontent.com/16406319/47085926-70e67680-d218-11e8-89b2-d41e14311e7b.png)

3. Update the page with the new fields

4. Results : all the fields are now empty...
![screen3](https://user-images.githubusercontent.com/16406319/47085996-9c696100-d218-11e8-9e45-5f86ae13c142.png)

If anyone could help me, it would be really appreciated 👍

**Comment by atanas-angelov-dev** [comment]
Hi @rosoam , could you please share your module definitions so that we can try and reproduce the issue?

**Comment by rosoam** [comment]
Hello @atanas-angelov-dev !

I found the solution about my issue.

In fact, I putted some uppercase characters in my fields variable definitions. 

I changed them to some lower case characters and that resolved the issue I had!

Thank you and I hope it maybe will help someone with the same issue in the future!
