### ISSUE TITLE
frontend-bundle.min.js being loaded even when a user is not logged in

### ISSUE THREAD

**Issue by ketanshah79** [elegantthemes/create-divi-extension#187]
### Problem Description
The frontend-bundle.min.js per plugin having divi modules has the necessary javascript code needed for the divi modules belonging to that plugin while editing in the divi frontend builder.

1. Why do we need these files when a user is not logged in? It adds unnecessary weight and server requests.
2. A user who has edit permissions for the page and who is logged in should only have these files loaded. 
3. Divi also loaded frontend-builder-scripts-[hashcode].js on non-logged page, which I think is for the core modules. Again not needed. 

### Steps To Reproduce
1. Visit https://www.diviframework.com/ . Make sure you are not logged in.
2. Open "Developer Tools", click on the "Network" tab and select "js" filter. 
3. Reload the page. You will see the javascript requests for the above files. 

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/119186/47477595-a6581900-d843-11e8-8d49-4efcf5f3133a.png)

**Comment by atanas-angelov-dev** [comment]
Hi @ketanshah79 ,

The `frontend-bundle.min.js` file contains scripts that modules need for rendering on the frontend (hence the name) and not in the **Visual Builder** so it's always loaded, regardless of who visits the page (there is a separate `builder-bundle.min.js` file loaded for the Visual Builder only).

https://www.diviframework.com/wp-content/plugins/df-vr-view/scripts/frontend-bundle.min.js specifically seems to be "empty" (only includes module loading boilerplate), i.e. the module does not really need any frontend JS, but it still enqueues the file. By default, `create-divi-extension` creates a module which enqueues a frontend scripts bundle for convenience but if the final module does not need to do so, you can disable the behavior by dequeuing the bundle in your extension class:
```php
public function __construct( $name = 'my-custom-module', $args = array() ) {
    $this->plugin_dir     = plugin_dir_path( __FILE__ );
    $this->plugin_dir_url = plugin_dir_url( $this->plugin_dir );

    parent::__construct( $name, $args );
    // Add the following line and define the dequeue_frontend_bundle method:
    add_action( 'wp_enqueue_scripts', array( $this, 'dequeue_frontend_bundle' ), 11 );
}

/**
 * Dequeue the frontend bundle as this extension does not need JS in the frontend.
 *
 * @return void
 */
public function dequeue_frontend_bundle() {
    wp_dequeue_script( "{$this->name}-frontend-bundle" );
}
```

Hope that helps :)

**Comment by ketanshah79** [comment]
thanks @atanas-angelov-dev 

I failed to bring to your attention other issue related to this.

![image](https://user-images.githubusercontent.com/119186/47556032-007fd980-d92b-11e8-87e4-fe37adef6833.png)

Please refer to the screenshot above.

The plugin with slug **divi-framework-breadcrumbs** have 4 divi modules in it, hence the script is loaded 4 times.
The plugin with slug **df-vr-view** has 1 divi module in it, hence the script is loaded once. 

Any idea why thats happening?

Thanks

**Comment by atanas-angelov-dev** [comment]
I'm assuming you have 4 different files in the `includes/` directory which extend the base `DiviExtension` class - you should only have 1 of those. The naming might be a bit confusing - the class represents your extension/plugin as a whole, while separate modules are inside `includes/modules/*`.

Let me know if this clears things up or if I'm missing anything.

**Comment by ketanshah79** [comment]
Thanks.

Just to confirm, for a single plugin, one should have one class extending
DiviExtension class even if there are more than one modules in the same
plugin?

**Comment by atanas-angelov-dev** [comment]
Yes :)
