### ISSUE TITLE
can't use "on" mode in custom blog module in child theme

### ISSUE THREAD

**Issue by AmeliePoulain92** [elegantthemes/create-divi-extension#188]
### Problem Description

hello guys, i'm using the latest divi theme and i've created a child theme.

### Steps To Reproduce
1. added folder called custom-modules
2. added new module called Test.php
3. added such code to functions.php:

`function divi_child_theme_setup() {
   if ( class_exists('ET_Builder_Module')) {
      include 'custom-modules/Test.php';
      $test = new ET_Builder_Module_MW_Test();
      remove_shortcode( 'et_pb_test' );
      add_shortcode( 'et_pb_test', array($test, '_shortcode_callback') );
   }
}
// add_action('wp', 'divi_child_theme_setup', 9999);
add_action( 'et_builder_ready', 'divi_child_theme_setup' );`
4. new module was created but it's working in partial mode. not in "on" if i hit "on" it shows me an error: http://prntscr.com/layei2
5. i'm extending the "ET_Builder_Module_Blog". and it's working but i can't edit the styles and it's working only in partial mode. Also when i switch it to a grid layout it adds opacity: 0 and it's hidden.

PS: please help me to fix that. thanks

**Comment by atanas-angelov-dev** [comment]
Hi @AmeliePoulain92 ,

You need to have a React class which represents your module in the Visual Builder or you cannot switch the support to "on".
Please use `create-divi-extension` (readme: https://github.com/elegantthemes/create-divi-extension) as this is the officially supported way to adding custom modules to Divi.
