### ISSUE TITLE
Divi 3.18.2  builder-bundle bug? Uncaught TypeError: Cannot read property 'guid' of undefined

### ISSUE THREAD

**Issue by mrkenng** [elegantthemes/create-divi-extension#201]
### Problem Description
On the latest Divi 3.18.2 today, Did a yarn build for production build.  

activated plugin on staging site and trying to edit the module and got this. Is there a known issue with the current Divi version with the developer API and got this.

```
Uncaught TypeError: Cannot read property 'guid' of undefined
    at v (<anonymous>:306:1429)
    at t.U (builder-bundle.min.js:1)
    at t.value (builder-bundle.min.js:1)
    at builder-bundle.min.js:1
    at builder-bundle.min.js:1
    at HTMLDivElement.t (builder-bundle.min.js:1)
```

Any ideas? 

### Steps To Reproduce
1.

**Comment by mrkenng** [comment]
Here's the line that the line

`"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=_;var e=o(require("lodash/debounce")),n=o(require("lodash/includes")),t=o(require("lodash/isString")),i=o(require("lodash/keys")),r=o(require("lodash/forEach")),d=o(require("lodash/remove")),u=o(require("lodash/isEmpty")),a=o(require("lodash/assign"));function o(e){return e&&e.__esModule?e:{default:e}}var l={},s={};function f(){var e=jQuery._data(window,"events");e.resize&&(0,r.default)(e.resize,function(e){e.handler._et_wrapped||(e.handler=w(e.handler))})}function w(n){var t=arguments.length>1&&void 0!==arguments[1]&&arguments[1],i=!n.cancel,r=!1,d=function(e,t){if(t&&n.flush)n.flush();else if(!window.ET_Builder.API.State.View_Mode.isAnimating())return n.apply(this,arguments)};i&&(d=(0,e.default)(d,350,{leading:!1}));var u=function(e){window.ET_Builder.API.State&&(!r&&window.ET_Builder.API.State.View_Mode.isAnimating()?r=!0:r&&!window.ET_Builder.API.State.View_Mode.isAnimating()?(r=!1,d.flush?d.flush():d.call(this,e,!0)):d.call(this,e))};return n._et_wrapped=!0,u.guid=n.guid||(n.guid=jQuery.guid++),u._et_wrapped=!0,t&&(s[u.guid]=u),u}function c(e,n){var t;"resize"!==e||n._et_wrapped||(n=w(n,!0));for(var i=arguments.length,r=new Array(i>2?i-2:0),d=2;d<i;d++)r[d-2]=arguments[d];return(t=l.window.addEventListener).call.apply(t,[window,e,n].concat(r))}function v(e,n){var t;"resize"===e&&n._et_wrapped&&(n=s[n.guid],delete s[n.guid]);for(var i=arguments.length,r=new Array(i>2?i-2:0),d=2;d<i;d++)r[d-2]=arguments[d];return(t=l.window.removeEventListener).call.apply(t,[window,e,n].concat(r))}function h(e,a){var o=arguments.length>2&&void 0!==arguments[2]?arguments[2]:null,s=arguments.length>3&&void 0!==arguments[3]?arguments[3]:null,f=jQuery.isWindow(this[0]),c=(0,t.default)(e),v=c?(0,n.default)(e,"resize"):(0,n.default)((0,i.default)(e),"resize");if(!f||!v)return l.jquery.on.apply(this,arguments);if(null===o&&null===s?(s=a,o=a=void 0):null===s&&(0,t.default)(a)?(s=o,o=void 0):null===s&&(s=o,o=a,a=void 0),c){var h=e.split(" "),p=(0,d.default)(h,function(e){return(0,n.default)(e,"resize")}),_=w(s);e=h.join(" "),l.jquery.on.call(this,p.join(" "),a,o,_)}else(0,r.default)(e,function(e,t){(0,n.default)(t,"resize")&&(e=w(e))});return(0,u.default)(e)?void 0:l.jquery.on.call(this,e,a,o,s)}function p(e){var t=this.attr("style");return(0,n.default)(t,e)?this:(this.css("cssText","".concat(t," ").concat(e)),this)}function _(){jQuery.fn.on=h,jQuery.fn.cssText=p,window.top&&(window.top.jQuery.fn.cssText=p),window.addEventListener=c,window.removeEventListener=v,f()}document.addEventListener("DOMContentLoaded",function(){(0,a.default)(l,{jquery:{on:jQuery.fn.on},window:{addEventListener:window.addEventListener,removeEventListener:window.removeEventListener}})});
`

**Comment by mrkenng** [comment]
I tested between the theme 3.17.6 and 3.18.2 and I can say that rolling back to Divi 3.17.6 does not have this error showing up.

**Comment by lots0logs** [comment]
Let's track this on #202

**Comment by mrkenng** [comment]
Thanks. Will track that over there 👍

**Comment by mrkenng** [comment]
Hi @lots0logs not sure if this is going to do with the #202 but just an update on my end. this is what i got again with the latest Divi as well. 
![Uploading Screenshot 2018-12-13 at 4.41.23 PM.png…]()
<img width="1298" alt="screenshot 2018-12-13 at 4 44 10 pm" src="https://user-images.githubusercontent.com/9147887/49926400-6eda2480-fef6-11e8-8b7a-52ecbdb1af43.png">

**Comment by Luke-SF** [comment]
I see this in a completely different Javascript application within Wordpress >5.5.

Uncaught TypeError: can't assign to property "guid" on true: not an object.

It seems it could be related to some sort of Backbone js Wordpress related changes?
