### ISSUE TITLE
Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

### ISSUE THREAD

**Issue by dmcshehan** [elegantthemes/create-divi-extension#204]
I'm getting the following error when running 'docker-compose up -d',

`ERROR: for e912545181a4_divi-api_wordpress_1  Cannot start service wordpress: driver failed programming external connectivity on endpoint e912545181a4_divi-api_wordpress_1 (9f93615b13e583b25005a12ef0a3617c46f755eac5f45e83c3a65ce9d987de90): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)`

any idea how to fix this? Im on a Mac.

**Comment by lots0logs** [comment]
Looks like you have a webserver running already that is using port 80. Be sure to exit any other dev environments you have running first.
