### ISSUE TITLE
How to setup default value of content in JSX

### ISSUE THREAD

**Issue by themohdarif** [elegantthemes/create-divi-extension#208]
### Problem Description
I would like to set up the default value of the module in visual builder when a user adds the module on the page. For example, when a user adds blurb module Divi setup default value. I'm able to set up text and other fields but unable to set up default values of the content block. 
I do not want to set up default values when a user adds a module in the backend. 
`			'content' => array(
				'label'                 => esc_html__( 'Content', 'et_builder' ),
				'type'                  => 'tiny_mce',
				'option_category'       => 'basic_option',
				'toggle_slug'           => 'main_content',
				'description'           => esc_html__( 'Input the main text content for your module here.', 'et_builder' ),
				'default'				=> 'Some default value',
			),`
This is not something, I'm looking for. I want default value only for visual builder.
### Steps To Reproduce
1. Add Blurb module on visual builder. This will publish some default values for content area. If you save module. It will save these values. 
2. Add Blurb module on backend. There is no default values. If we follow above approach this will add default values for backend as well and I do not want so. 

Just need an idea how to achieve this for TinyMCE.

Many Thanks,

**Comment by xxtesaxx** [comment]
You can inject defaults in the VB by extending the window.ETBuilderBackend.defaults.

The property is your module slug and it contains a object containing the fields for which you want to inject defaults.

Take for example the following JS code I put in the frontend.js file:

```
jQuery(function($) {
    window.ETBuilderBackend.defaults.dss_my_module = {
        test: "Hello World, does this work?"
    };
});
```

In my module (with the slug "dss_my_module") I defined the setting field as follows:

```
$settings["test"] = [
    'label' => esc_html__('Test', 'ds-suit'),
    'type' => 'text',
    'default' => '',
    'option_category' => 'basic_option',
    'tab_slug' => 'general',
    'toggle_slug' => 'text',
];
```

Adding a new module in the VB will now have the default set. When clicking the field reset button, it defaults back to the empty default I configured in the field definition. One thing to keep in mind is that even if you set a default other than empty, the JS default will overwrite it.

If you need translated texts or other php values in the frontend.js, it's up to you to find a way to pass those. I guess one way would be to do it like Divi does it, echoing JavaScrip, probably in the head action hook. 

Another technique could be to enqueue your own scripts and use the good old translation technique to inject your values from php into the JS.

**Comment by themohdarif** [comment]
This is working for me. Thank you so much for this solution. You made my day!!
Happy holidays!! 👍

**Comment by xxtesaxx** [comment]
It would be cool if we could define VB defaults directly on the field inside our module definition
