### ISSUE TITLE
Help : How build a divi module from a subfolder

### ISSUE THREAD

**Issue by gonzalesc** [elegantthemes/create-divi-extension#209]
Hi
I have a plugin and Im creating blocks/modules/elements in VisualComposer, Gutenberg and Elementor.
Now I want to create a Divi module to my plugin but "create-divi-extension" is to buil a extension from raiz.

I will buil the module in a subfolder and the problem is, it will create a node_module and package.json there too ... everything will be messy.

How can I sort this files to my convenience? Could I only create a module without create a extension?

Regards

**Comment by themohdarif** [comment]
If you want this: YourPluginName -> FolderForDiviModule
You can walk through inside this folder and put package.json(You have to create one manually) inside your intended folder. After this manually run **npm install** command. This will install all dependencies.
