### ISSUE TITLE
How to make wp-pagenavi pagination work on VB?

### ISSUE THREAD

**Issue by khurana-ankur** [elegantthemes/create-divi-extension#212]
### Problem Description
Created the pagination but it's not working.

### Steps To Reproduce
1. Add default divi blog module on VB with wp-pagenavi.
2. It will add pagination which is loading next posts. I would like to achieve the same functionality on my custom module. Is there any Elegant theme api available for this?

**Comment by xxtesaxx** [comment]
I guess no but you could implement this with some JavaScript and an Ajax call
