### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by snewsh** [elegantthemes/create-divi-extension#215]
### Problem Description
Hi Guys.
Midway through building a module in 3.17.x and everything was working well. Updated to 3.19.4 and it's broken. All I get in the visual builder is an error. (see screenshot).
Any ideas. Thank you.

### Screenshot and/or gif
![screen shot 2019-01-09 at 09 34 16](https://user-images.githubusercontent.com/43791070/50890633-75bf5e80-13f2-11e9-859f-c69cc4d1caf2.png)

**Comment by snewsh** [comment]
Thanks but mine is already http. It's so frustrating. Not nearly enough documentation or help from Elegant Themes for developers.

**Comment by lots0logs** [comment]
Did you update to the latest version of create-divi-extension? (See the readme for details on updating.)

**Comment by snewsh** [comment]
Thanks Dustin. I've followed the instructions in the changelog.md
I ran 'yarn add --exact react-scripts@1.1.1' which adds a react-scripts dependency to the package.json file but doesn't seem to update divi-scripts. Unfortunately, yarn start now throws errors and when I run 'npm ls jest' I get an unmet dependency error (jest@22.1.2). Any further thoughts?
Simon.

**Comment by lots0logs** [comment]
Ah, looks like I missed a spot when changing all `react-scripts` references to `divi-scripts`. You shouldn't install `react-scripts`. You should just put the latest version of `divi-scripts` in your `package.json` and then run `yarn`.

**Comment by lots0logs** [comment]
I commented on the other issue :smile:
