### ISSUE TITLE
Add a tab to ePanels current tabs

### ISSUE THREAD

**Issue by jamesfosker** [elegantthemes/create-divi-extension#219]
I know there is a way to add new main tabs to ePanel but is there a way to add a new tab under one of Divi default tabs, such as integration.

I would like to add a new sub-tab under the integration tab.

**Comment by xxtesaxx** [comment]
Yes this is possible though its not so trivial. You have to implement the et_epanel_layout_data filter and then split the array at the right location and insert your own sub-tab and fields. 

I believe the child theme generator from Elegant Marketplace has a sample of how to inject settings on the main tab. The same technique can be used to inject the sub-tab beforehand.

**Comment by lots0logs** [comment]
There's an example of how to do it in: `includes/builder/class-et-builder-settings.php`.  The two filters are on lines 714 & 715. You can find their callbacks in that same file.

**Comment by jamesfosker** [comment]
@lots0logs awesome thanks
