### ISSUE TITLE
Full width modules React error.

### ISSUE THREAD

**Issue by charles890123** [elegantthemes/create-divi-extension#222]
### Problem Description
I have two extensions one with full support and another with partial support. These two extensions have more than one module and at least one of the modules is a full width module. When I add the module to a full width section on the Visual Builder or the New Divi Builder and then try to add another module after I get the wrong list of modules, instead to see the full width module I get the list of standard modules, if I add one of the standard modules then happens a React error.

### Steps To Reproduce
1. I also test with the https://github.com/elegantthemes/divi-extension-example and add a line of code to the Custom CTA VB module $this->fullwidth = true; to make the module available on the full width section and I was able to replicate the issue.

https://dividevs.slack.com/archives/CA9FV3HPB/p1545166446081300

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/16024719/51180730-2f0cb100-1897-11e9-9e4d-4e5272f13e86.png)

![image](https://user-images.githubusercontent.com/16024719/51180688-008ed600-1897-11e9-97e2-475fc51b6ccd.png)

### PR
https://github.com/elegantthemes/submodule-builder/pull/5804

**Comment by charles890123** [comment]
Hello @bitfade Any updates here?

**Comment by VladET** [comment]
This is working as expected with the latest version of Divi. Closing.
