### ISSUE TITLE
Get all modules

### ISSUE THREAD

**Issue by gonzalesc** [elegantthemes/create-divi-extension#227]
Hi.
Im using the hook "`et_pb_all_fields_unprocessed_{module-slug}`" and it works great!

But I need put a field in all the modules (include child modules) and I tried use these methods:

```
ET_Builder_Element::get_modules_array('page', true);
ET_Builder_Element::get_modules_i10n('page');
ET_Builder_Element::get_modules('page', 'parent');
ET_Builder_Element::get_parent_and_child_modules('page');
```

And all those method return empty.

Do you have some sugestion for me, to do it?

**Comment by lots0logs** [comment]
Hi, I'm afraid it's not currently possible to modify fields in all modules at once. You would have to add that  filter for every module. The filters have to be added before the modules have been initialized so you'll probably have to hardcode a list of module slugs into your extension. Maybe you could generate the list dynamically by looping through the module files, worth a try before hard coding anyway.

**Comment by gonzalesc** [comment]
Ok. I had to create a array with all the modules for default.

Thanks
