### ISSUE TITLE
show_if display logic parentModule not working on Old Classic Builder

### ISSUE THREAD

**Issue by mrkenng** [elegantthemes/create-divi-extension#231]
### Problem Description
When using 'show_if' => array( 'parentModule:element' => 'on') on your child module will not work on old classic builder. It just wont open up when clicking on 'Add New Item + '
 
Error showing up on console is: 

`Uncaught Error: Syntax error, unrecognized expression: unsupported pseudo: element`

Anyone else having this issue?

**Comment by lots0logs** [comment]
I'm afraid that functionality is not available on the Classic Divi Builder. Sorry!
