### ISSUE TITLE
Setup React-Extension with custom ReactJs

### ISSUE THREAD

**Issue by pirminb97** [elegantthemes/create-divi-extension#234]
### Problem Description

I followed the steps in the tutorial andd created a divi extension, which displays php code with react styling it.

**The Problem:**
Im wondering if there is a possibility to just display the content from the react side.
In the live website the react script is not loaded and i want to add some logic like fetching from wordpress API to my ReactApp.
Currently the repsonsibility to render HTML seems to lay on php.
If anyone can help, that would be nice...

**Comment by xxtesaxx** [comment]
At the moment you have to write the rendering code twice. For the Visual Builder, you write the code in your react module. For the frontend though, you use the php module. 

If you want to run a react app on the frontend, you could in your php module, render an empty div with your settings as a json parsed attribute and then use your own javascript logic to display content inside that div.

**Comment by markospacetech** [comment]
Hi is there any chance that you'd have some resource(s) on how to achieve this?
