### ISSUE TITLE
Sub Toggles

### ISSUE THREAD

**Issue by snewsh** [elegantthemes/create-divi-extension#235]
Hi. 
I am trying to add a color field to a number of sub toggles. I can add it to one sub toggle without issue but can't add an array of sub toggles. Am I doing something wrong? Is this normal behaviour and if so, is there another way of doing it?

Thank you
![screen shot 2019-02-20 at 10 38 56](https://user-images.githubusercontent.com/43791070/53086404-f3e84800-34fc-11e9-915a-6d2c52926e1a.png)

**Comment by xxtesaxx** [comment]
A setting field can only be part of one toggle/sub toggle. 

If you are looking for something similar to the text settings where you can switch between h1-h6 and certain settings stay the same, you might want to look into composite fields.
