### ISSUE TITLE
403 Forbidden when running in local

### ISSUE THREAD

**Issue by RendyTan** [elegantthemes/create-divi-extension#236]
### Problem Description
After following the guide in https://www.elegantthemes.com/documentation/developers/divi-development-environment/, accessing http://local.divi-dev.site leads to 403 Forbidden error with message `You don't have permission to access / on this server.`

My Environment is:
Mac OS High Sierra
Apache/2.4.33
mysqld 10.3.13-MariaDB

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/11849819/53285750-de8e4a80-3796-11e9-8df3-2252117889db.png)
![image](https://user-images.githubusercontent.com/11849819/53285758-f665ce80-3796-11e9-8367-1064e5cf0333.png)

**Comment by lots0logs** [comment]
It looks like you have a webserver running on your system other than the divi dev docker container. You should terminate that webserver process before starting the divi dev docker container.

**Comment by xxtesaxx** [comment]
Or change the ports of the container

**Comment by zjh055** [comment]
Hello, apologies for posting here over a year later, but I am having the exact same issue running Windows 10 Home. I have followed the guide like the original poster, successfully downloaded WordPress and when I go to local.divi-dev.site I am getting a 403 Forbidden error. How would I go about terminating other webserver processes? To my knowledge all I am currently running is the divi dev docker container. If anyone provide any further guidance it would be greatly appreciated. 


![Screenshot (19)](https://user-images.githubusercontent.com/9739646/88476323-b909f100-cef4-11ea-8af0-edb36090266c.png)

![Screenshot (21)](https://user-images.githubusercontent.com/9739646/88476330-c32bef80-cef4-11ea-9ef6-34f08836f220.png)
