### ISSUE TITLE
Frontend Builder Not working

### ISSUE THREAD

**Issue by jayyogvihalkrupa** [elegantthemes/create-divi-extension#237]
### Problem Description
after upgrade latest theme 3.19.18 when edit content on front end builder module got " function (t){return s.a.createElement(p.a,g({rawContentProcesser:_.a.replaceCodeContentEntities},e.props))}" Message. Have started yarn

yarn-1.7.0
node-v8.11.3
Window 10
Xampp

Also tried with latest Node and Yarn Face same issue

### Steps To Reproduce
1.

### Screenshot and/or gif
https://prnt.sc/mrpkge
https://prnt.sc/mrpkij

**Comment by xxtesaxx** [comment]
delete node_modules folder, possible lock files and run npm install again. Make sure that after running yarn start, your wp-config.php contains the debug switch with the prefix of your module. Clear your browsers cache and reload.

**Comment by jayyogvihalkrupa** [comment]
Thank you much for your help and support . After add manually debug mode on wp-config.php file.it works fine. define( 'DITE_DEBUG', true )
