### ISSUE TITLE
Library module images not rendering

### ISSUE THREAD

**Issue by snewsh** [elegantthemes/create-divi-extension#238]
### Problem Description
I have created a module which uses images which works as expected when the module is created on the intended website. If I create a module on one website (local server), save it as a library item, export and import to a different website (live), the image doesn't render because it is still pointing at the original source (local server). The media library doesn't get updated like it does with the ET image module. Any advice would be gratefully received or a point in the right direction to any documentation.
Thank you.

**Comment by xxtesaxx** [comment]
Looks like a bug in the export from the library. A possible workaround would be: add the module on an new empty page, export the page layout, import the page layout on the live site, save the module to the library and delete the site.

**Comment by snewsh** [comment]
Thanks Jan, I’ve tried various methods of exporting and importing modules and page layouts including this idea. Unfortunately, the original image url remains unchanged and the image doesn’t get imported into the Wordpress media library like it does with the ET image module.

Also thanks for replying to issue #235. I found an acceptable solution for this.

Simon

**Comment by xxtesaxx** [comment]
Can you post your field config?

**Comment by snewsh** [comment]
Couldn't post the whole config but the part that relates to the image is here (unsure if that's what you need)
			//Image Upload
			'dwic_image_upload' => array(
				'type'               => 'upload',
				'option_category'    => 'basic_option',
				'upload_button_text' => esc_attr__( 'Upload an image', 'dwci_image_clip' ),
				'choose_text'        => esc_attr__( 'Choose an Image', 'dwci_image_clip' ),
				'update_text'        => esc_attr__( 'Set As Image', 'dwci_image_clip' ),
				'hide_metadata'      => false,
				'affects'            => array(
					'dwic_alt',
					'dwic_title_text',
					'dwic_clipping_shapes',
					'dwic_image_opacity',
					'dwic_image_horizontal',
					'dwic_image_vertical'
				),
				'description'        => esc_html__( 'Upload your desired image, or type in the URL to the image you would like to display.', 'dwci_image_clip' ),
				//'toggle_slug'        => 'image',
				'option_category' => 'basic_option',
				'toggle_slug'     => 'settings',
				'sub_toggle'      => 'image',
			),

**Comment by xxtesaxx** [comment]
Hmm only difference to my image fields is the hide_metadata which I don't really think is necessary but thats surely only personal preference.

Strangely though for me both cases work. Exporting a layout via the library works just as well as via a page. 

Besides that, you should move forward from the old affects functionality to the new show_if functionality.

Oh an you defined option_category twice which will have no effect but it looks odd :P

**Comment by xxtesaxx** [comment]
Is there probably a mismatch between Divi versions on those systems? Can you check the exported layout if it contains the encoded image in the json. Something like: my-image.jpg":{"encoded":"\/9j\/7gAOQW...

**Comment by snewsh** [comment]
Both sites running version 3.19.15
Nothing in the json file which states 'encoded'
When you export and import a non-ET image module, does it update the Wordpress media library?

**Comment by xxtesaxx** [comment]
Yep

**Comment by snewsh** [comment]
Okay, thanks for looking at it for me Jan. It's obviously something I've done wrong somewhere if you're able to get it to work without adding anything special. I'll try to unpick it!
Thanks again.

**Comment by xxtesaxx** [comment]
Just send me the module (preferably without the nodes_module folder) via mail and I'll have a look

**Comment by xxtesaxx** [comment]
Hehe I found out whats the issue is. I also found a lot of familiar code in your plugin. Please make sure to remove it so your plugin doesn't cause side effects to mine. You can simply search for "dss_" ;) 

So the issue here is that apparently Divi only exports images from upload fields if the name of the field ends with image. All you need to do is remove the "_upload" and make sure the field is named "something_image" and you should be good to go.

**Comment by snewsh** [comment]
Thanks Jan. I'll try it tomorrow when I've got a bit more time. Hopefully, that will solve it. Yeah, learnt a fair bit from just looking through your code even though much of it is still above me. I'll strip it all out before release. Rather than a contribution I'll just purchase your course. I'm sure there will be a lot in there that will help me out. Any chance of a good discount ? :-)
Thank you so much for your time.

**Comment by xxtesaxx** [comment]
Ahh too bad. :) I have so many ideas for little free modules and only so
much time. I can offer you a 50% discount though:
https://www.udemy.com/divi-dojo/learn/v4/?couponCode=SIMON50

Am Mo., 4. März 2019 um 22:08 Uhr schrieb snewsh <notifications@github.com>:
