### ISSUE TITLE
changing module slugs

### ISSUE THREAD

**Issue by jamesfosker** [elegantthemes/create-divi-extension#245]
Is there a way to change slugs, I'm busy updating a plugin which I made ages ago with modules for example et_pb_add_to_cart I am wanting to change the module slug to something different to avoid conflict with your woocommerce update.

is there a way to migrate slugs?

**Comment by lots0logs** [comment]
No, I'm afraid not. We have never needed to change the slug of a module so we don't have anything implemented to handle that. You would have to do it from within your plugin code. Ideally you would inform the user that your plugin needs to update the posts that contain your module and ask them to confirm. Then you would go through all the posts and replace all instances of your slug with the new slug in the content. Hope that helps!
