### ISSUE TITLE
Button advanced field defaults

### ISSUE THREAD

**Issue by jcdotnet** [elegantthemes/create-divi-extension#247]
### Problem Description
After reading the documentation and going over all the related issues I'm still unable to set the default values for this advanced field. For example, what if we want 0 for the button border width defatult? 

Thanks in advance.

### Steps To Reproduce
1. Set the button border default to 0.

**Comment by lanresmith** [comment]
@jcdotnet kindly check this out:
```
'button'  => array(
				'button' => array(
					'label'               => esc_html__( 'Follow Button', 'et_builder' ),
					'css'                 => array(
						'main' => "{$this->main_css_element} .follow_button",
					),
					'hide_icon'           => true,
					'hide_custom_padding' => true,
					'no_rel_attr'         => true,
					'text_size'           => array(
						'default' => '14px',
					),
					'border_width'        => array(
						'default' => '0px',
					),
					'box_shadow'          => array(
						'css' => array(
							'main' => "{$this->main_css_element} .follow_button",
						),
					),
				),
			),
```

notice the `border_width` default value. This can be found in `includes/builder/module/SocialMediaFollow.php` of your Divi theme folder. More info about possible default values for button advanced fields can be found in the `_add_button_fields` method of the `ET_Builder_Element` class in `includes/builder/class-et-builder-element.php`.
