### ISSUE TITLE
NPM Start is not updating live changes now

### ISSUE THREAD

**Issue by munirkamal** [elegantthemes/create-divi-extension#249]
### Problem Description
Recently I am experiencing an issue while building custom 3rd party divi extensions using create-divi-extension. I keep NPM start running and now it is not reflecting the changes I am making in JSX to the site. I have to run npm run build and then the changes apply to the website. 

I Wonder if this is a bug or some issue at my end? However, I've tested it on a couple of different machines with different divi custom plugins I built. 

### Steps To Reproduce
1. Simply run "npm start" make any changes to JSX of the module and see if the changes apply to the website or not. 

____
### Attached PR
* https://github.com/elegantthemes/create-divi-extension/pull/257

**Comment by pbov** [comment]
Same issue here - but with "yarn start"...

**Comment by munirkamal** [comment]
Any updates on this?
