### ISSUE TITLE
Divi and Laravel Integration

### ISSUE THREAD

**Issue by carlosmirandazurilla** [elegantthemes/create-divi-extension#250]
### Problem Description

Hello!

I would like to create a website using the Divi theme and then extract the source code to integrate it with a Laravel project I am developing. What libraries/frameworks/dependencies do I have to download to my Laravel project so that my Divi website runs as it does on Wordpress?

Thanks!

**Comment by lots0logs** [comment]
Divi's only dependency is WordPress itself. I'm not sure what it is exactly you are trying to achieve though. Could you elaborate?

**Comment by carlosmirandazurilla** [comment]
I want to download the source code for a website I created on Divi and use it on my own project which is e-commerce on Laravel. Is this possible? Does Divi have any JS libraries/frameworks such as React that I have to download on my project on Laravel to make the website run seamlessly? I would have to grab the HTML code and create the new views on my Laravel project, but is there anything else I have to do for the website animations/transitions my website has?

Thanks!

**Comment by lots0logs** [comment]
The HTML output of the pages will have all the necessary css and javascript files included as `<link>` and `<script>` elements. You would just need to update the path to the correct location of the files on your server.

**Comment by carlosmirandazurilla** [comment]
@lots0logs thanks!
