### ISSUE TITLE
Fullscreen JSX code required

### ISSUE THREAD

**Issue by snewsh** [elegantthemes/create-divi-extension#258]
### Problem Description
I am creating a module which will be fullscreen. In PHP I can add the class "et_pb_fullscreen" which adds the attribute style="min-height:830px;" and this works correctly but adding the same className in JSX doesn't add the attribute. Any ideas folks? Thank you.

**Comment by snewsh** [comment]
Okay, so I've found that the attribute is added when the module is saved and the page refreshed but it adds a different min-height:844px
Really need to see JSX code. So wish Elegant Themes would release them!

**Comment by petejacobson** [comment]
+1 for releasing the JSX files

**Comment by Paul-S-Taylor** [comment]
+1 for releasing the JSX files (been asking for over a year)

**Comment by superjordi** [comment]
+1 :D <3

**Comment by lots0logs** [comment]
Sorry for the delayed response. We have an issue opened already regarding the JSX files so I'm going to close this one.
