### ISSUE TITLE
Is there a way to limit amount of module's children? 

### ISSUE THREAD

**Issue by runnickrun** [elegantthemes/create-divi-extension#259]
### Problem Description
I would like to limit amount of children to a fixed number, e.g. 3 min and 6 max. Is there a way to do it?

This was asked in #67, but with no answer.

**Comment by xxtesaxx** [comment]
It is not possible though you could, when rendering, simply ignore too many items. However, for the user this might get confusing.

**Comment by runnickrun** [comment]
Yeah, we decided go with non-dynamic block for that (with 6 inputs). Although it would be great to have that limit option on children as it's confusing in terms of ux.
