### ISSUE TITLE
Win10 Pro :: Container for Service WordPress :: invalid volume specification

### ISSUE THREAD

**Issue by Mizagorn** [elegantthemes/create-divi-extension#26]
### Is this a bug report?

Yes

### Did you try recovering your dependencies?

Have not reached the point of being able to recover dependencies.

### Which terms did you search for in User Guide?

The README.md does not contain troubleshooting regarding running the divi-dev package on docker.

### Environment

1. `node -v`: n/a
2. `npm -v`: n/a
3. `yarn --version` (if you use Yarn): n/a
4. `npm ls react-scripts` (if you haven’t ejected):  n/a

Then, specify:

1. Operating system: Windows 10 Pro Build 16299.371 Fall Creators Update
2. Browser and version (if relevant): n/a

### Steps to Reproduce

(Write your steps here:)

1. I am following instructions at https://www.elegantthemes.com/documentation/developers/divi-development-environment/
2. Docker installed and running properly
3. Created docker-compose.yml as specified in the instructions
3. Using Powershell. Since '&&' is not a valid statement operator in Windows Powershell, I ran the first command by itself as such: docker-compose up -d

### Expected Behavior

I expected that all packages required to get a development environment would be set up and ready to use, then I was going to run the second docker-compose command.

### Actual Behavior

**This is the text of the result:** Note that I am using a folder under /users/ as specified in the instructions on a Windows machine.
PS C:\users\terry\docker> docker-compose up -d
WARNING: The PWD variable is not set. Defaulting to a blank string.
Creating network "docker_default" with the default driver
Creating volume "docker_database" with default driver
Pulling wordpress (elegantthemes/divi-dev:latest)...
latest: Pulling from elegantthemes/divi-dev
c3b9c0688e3b: Pull complete
e9fb5affebb0: Pull complete
0f1378f511ad: Pull complete
96a961dc7843: Pull complete
16564141bc83: Pull complete
724e678ab34e: Pull complete
babef1eb7436: Pull complete
053e50a05e95: Pull complete
afa6ca93bcaa: Pull complete
c403799400eb: Pull complete
d925564d019e: Pull complete
28a79d3f0370: Pull complete
Digest: sha256:625c5bc769f9773a319ecb40e955c54fc8fbec5dceb0799fa94089438048b804
Status: Downloaded newer image for elegantthemes/divi-dev:latest
Pulling mariadb (mariadb:10.2.14)...
10.2.14: Pulling from library/mariadb
f2b6b4884fc8: Pull complete
26d8bdca4f3e: Pull complete
74f09e820cce: Pull complete
5390f1fe4554: Pull complete
3d3f1706a741: Pull complete
2942f66426ea: Pull complete
97ee11d39c75: Pull complete
590c46ef722b: Pull complete
32eb4b9666e5: Pull complete
fc883f98a064: Pull complete
bb8bee61bc1e: Pull complete
Digest: sha256:6135f5b851e7fe263dcf0edf3480cdab1ab28c4287e867c5d83fbe967412ea14
Status: Downloaded newer image for mariadb:10.2.14
**Creating docker_wordpress_1 ... error**

ERROR: for docker_wordpress_1  Cannot create container for service wordpress: invalid volume specification: '/host_mnt/workspace/wordpress:rw'

ERROR: for wordpress  Cannot create container for service wordpress: invalid volume specification: '/host_mnt/workspace/wordpress:rw'
ERROR: Encountered errors while bringing up the project.

### Reproducible Demo

I tried uninstalling Docker and trying again with a fresh install. I don't know how to describe something that can be reproduced since I'm not actually trying to create an extension yet.

**Comment by Mizagorn** [comment]
As mentioned above regarding '&&'... since Docker for Windows shows Powershell examples, you might want to specify a separate two commands at https://www.elegantthemes.com/documentation/developers/divi-development-environment/

As such:
PS C:\users\terry\docker> docker-compose up -d && docker-compose exec -u 1000 wordpress divi-dev setup
At line:1 char:22
+ docker-compose up -d && docker-compose exec -u 1000 wordpress divi-de ...
+                      ~~
**The token '&&' is not a valid statement separator in this version.**
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

Just a suggestion. 😄

**Comment by lots0logs** [comment]
Could you try running the commands from inside [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)? The config expects the `PWD` environment variable to be set which is why its failing. Also IIRC, instead of `docker-compose` you will need to use `docker-compose.exe` when running the command.

**Comment by Mizagorn** [comment]
Thanks @lots0logs! I gave that a whirl and got really close, but never actually got it all sorted out. I wound up going with XAMPP and PowerShell, and that was only about a 45 minute process to get the whole thing set up. Things are working as expect now!
