### ISSUE TITLE
Get total children amount and each child's index.

### ISSUE THREAD

**Issue by runnickrun** [elegantthemes/create-divi-extension#260]
### Problem Description
Is it possible to get whole amount of children of the module and ideally each child's index?

**Comment by xxtesaxx** [comment]
Yes, there are ways to do this. In JSX for example, try to console.log the parents props. You should see that you can get access to the children there and simply iterate over them. In PHP for example you can use before_render to create a global array which you can access in the childs render(). Then in the childs render() put what you want into the global array and in the parents render() you now can access the array yet again to obtain what you need as well as an index.

```
//Called in parent. Runs before childrens render() is called. Childrens render() are called before parents render() is called
public function before_render() {
    global $my_items;
    $my_items = array();
}
```
