### ISSUE TITLE
Create Custom Field Type

### ISSUE THREAD

**Issue by alpezed** [elegantthemes/create-divi-extension#261]
Hi, Is there any option to create a custom field type? Can you please show me how can i create a custom field type or a documentation link. Thank You

**Comment by superjordi** [comment]
What kind of custom field? You can already. For example, you create a custom text field, and you can use it as an icon searcher. You can achieve this with some javascript. Hope it helps!

**Comment by alpezed** [comment]
Hi, Can you give me a sample or documentation please on how to create a custom field type or custom control like Elementor Builder https://developers.elementor.com/creating-a-new-control/.

**Comment by lots0logs** [comment]
Custom field types are not yet supported though they are planned for this year.
