### ISSUE TITLE
et_pb_generate_responsive_css() not working for 'color-alpha' field

### ISSUE THREAD

**Issue by IvanChiurcci** [elegantthemes/create-divi-extension#278]
### Problem Description
I enabled resposive settings for the `'color-alpha'` field and tried to generate the responsive CSS using the `et_pb_generate_responsive_css()` function but it did not work. 

The responsiveness is enabled in VB (tablet and phone tabs are activated and colors selected for all devices) but the problem is with the CSS generated ( and not generated :) ) on the frontend.

**Issue 1:** 
The responsive CSS is not being generated for tablet and phone on the frontend, but only for desktop. But that one is not applied neither because of the **issue 2** below.

**Issue 2 :**
There is a 0(zero) added to the color code which makes it invalid. For example, `#ffffff` is printed as `0#ffffff`, and if the color code contains a 0(zero) it gets removed, like this: `#8300e9` becomes `0#83e9`. The same happens to rgba color.

I am sure I'm missing something :) . Any help appreciated. Thanks.

### Steps To Reproduce
**1. Add the `color-alpha` field**

```
'header_bg_clr' => array(
	'label'           => esc_html__( 'Background Color', '' ),
	'type'            => 'color-alpha',
	'option_category' => 'basic_option',
        'mobile_options'    => true,
        'responsive'        => true,
        'custom_color'    => true,
        'description'     => esc_html__('Description.', ''),
        'default'         => '',
	'tab_slug'        => 'advanced',
	'toggle_slug'     => 'header_toggle',
),
```

**2. Implement the responsive CSS generation**

```
$header_bg_clr = $this->props['header_bg_clr'];
$header_bg_clr_tablet = $this->props['header_bg_clr_tablet'];
$header_bg_clr_phone = $this->props['header_bg_clr_phone'];
$header_bg_clr_last_edited = $this->props['header_bg_clr_last_edited'];

if ( '' !== $header_bg_clr_tablet || '' !== $header_bg_clr_phone || '' !== $header_bg_clr ) {
        $header_bg_clr_responsive_active = et_pb_get_responsive_status( $header_bg_clr_last_edited[0] );

        $header_bg_clr_values = array(
            'desktop' => $header_bg_clr,
            'tablet'  => $header_bg_clr_responsive_active ? $header_bg_clr_tablet : '',
            'phone'   => $header_bg_clr_responsive_active ? $header_bg_clr_phone : '',
        );

        et_pb_generate_responsive_css( $header_bg_clr_values, '%%order_class%% .header', 'background-color', $render_slug );
}

```

**Comment by ayubadiputra** [comment]
Hi @IvanChiurcci, there is new method to generate responsive settings and accept all field types. It's called `et_pb_responsive_options()->generate_responsive_css`. It has similar argument with `et_pb_generate_responsive_css` except additional parameter to determine what is the current field type to use here.

```
/**
 * Generates the css code for responsive options.
 *
 * Uses array of values for each device as input parameter and css_selector with property to
 * apply the css.
 *
 * Copy of et_pb_generate_responsive_css() with some modifications to improve.
 *
 * @since 3.23
 *
 * @param  array  $values_array   All device values.
 * @param  mixed $css_selector    CSS selector.
 * @param  string $css_property   CSS property.
 * @param  string $function_name  Module slug.
 * @param  string $additional_css Additional CSS.
 * @param  string $type           Value type to determine need filter or not. Previously, it only
 *                                accept value from range control and run a function to process
 *                                range value.
 * @param  string $priority       CSS style declaration priority.
 */
et_pb_responsive_options()->generate_responsive_css( $values_array, $css_selector, $css_property, $function_name, $additional_css = '', $type = 'range', $priority = '' );
```

For example, to process `color-alpha` field type, you need to pass `color` on the 6th argument.
```
et_pb_responsive_options()->generate_responsive_css( $open_toggle_background_color_values, '%%order_class%% .et_pb_toggle_open', 'background-color', $render_slug, '', 'color' );
```

**Comment by IvanChiurcci** [comment]
Thank you @ayubadiputra , this one works properly. Is there an equivalent JS function for VB part as well?

**Comment by ayubadiputra** [comment]
@IvanChiurcci Unfortunately, there is no similar Utils method available for 3PS yet. But, there is an open issue for that, you can follow it here https://github.com/elegantthemes/create-divi-extension/issues/115. Some people also discuss about responsive CSS here https://github.com/elegantthemes/create-divi-extension/issues/143, maybe it can help you.

Since the main question in current issue is answered, I will close it. Thank you.
