### ISSUE TITLE
et_module_shortcode_output rendering output issue after Divi 3.26. Had to roll back to 3.25.4

### ISSUE THREAD

**Issue by mrkenng** [elegantthemes/create-divi-extension#281]
### Problem Description
I'm using fields_unprocessed to add options to existing Divi modules using et_pb_all_fields_unprocessed_

I have a function that loads out the Divi Library(et_pb_layout) to the select field type.

```
$fields['divi_library'] = array(
            'label'            => esc_html__( 'Divi Library', 'et_builder' ),
            'type'            => 'select',
            'option_category' => 'layout',
            'default_on_front' => 'none',
            'tab_slug'        => 'custom_css',
            'toggle_slug'     => 'visibility',
            'options'           => divi_load_library(),
        );
```

During the output, var_dump($module->props['divi_library']) will come out with the ID of the library and it supposed to output the ID of the library which is working well until Divi updated to 3.26.  I guess this has something to do with the mechanism to allow to set site-wide section/row/module defaults from right inside the builder.

When I am in the Website-Wide Design Editor, surprisingly the selected Divi library ID is showing up on var_dump! et_module_shortcode_output. Exited Website-Wide Design Editor, did a var dump on $module->props['divi_library'] and the data cannot be found. it's like not saving the data. Can anyone confirm that Divi 3.26 is having this weird bug? 

And yes, it was working before 3.26
____
### Attached PR
* https://github.com/elegantthemes/submodule-builder/pull/6173

**Comment by mrkenng** [comment]
How can we not show up the option in Website-Wide Design Editor. I am suspecting this is the cause of it.

**Comment by Jronk** [comment]
The fix has been merged and will be included in the next release. 👍
