### ISSUE TITLE
3rd party modules that support specific post type render on other post types too

### ISSUE THREAD

**Issue by SailorAbood** [elegantthemes/create-divi-extension#29]
### Is this a bug report?

Yes! 

Details:

1- I'm talking about modules with $this->post_types = array( 'X_post_type' );
2- Let's say you have two post types X and Y
3- When you edit a post from Y, the module must NOT render in the builder.
4- The issue: If you have a saved layout in the library that contains that module, and you import this layout in a post from type Y, the module renders in BOTH back-end and front-end.

5- This issue started with Divi 3.1, it didn't happen before.

6- In Divi before 3.1, if you import the layout in post type Y and that layout has a module that only supports post type X, it will NOT render in the back-end nor the front-end. 

7- This screenshot shows the difference between Divi 3.1 and older
https://test.abdozo.com/wp-content/uploads/2018/04/Screen-Shot-2018-04-23-at-7.21.44-PM.png

### Steps to Reproduce

Steps above.

### Expected Behavior

A module that supports specific post should NOT be rendered on another post type, front-end and back-end.

And if a "saved layout" has that module and imported to a different post type, that module must be removed from the content just like before.

### Note

I opened a support ticket in Elegant Themes forums but the support agent asked to open an issue here.

**Comment by SailorAbood** [comment]
Hi, any updates on this one?

**Comment by lots0logs** [comment]
The fix for this is currently going through QA. It should make it into the next update :smiley:
