### ISSUE TITLE
Working with styles on Custom Divi Module

### ISSUE THREAD

**Issue by theoriginallegend27** [elegantthemes/create-divi-extension#294]
### Problem Description
I am trying to overwrite some attributes or what classes are loaded with the modules without using the style sheet because I am using SASS in my theme and I don't want to write every attribute with !important. It would be easier for me to understand how the style and classes are set up or to set a setting not to overwrite the theme

**Comment by xxtesaxx** [comment]
Thats just how CSS works. Instead of asking for complicated changes from Elegant Themes, just use stronger selectors in your SASS and you won't need any !important except if there are inline styles somewhere.
