### ISSUE TITLE
upload-gallery type

### ISSUE THREAD

**Issue by nathangemis** [elegantthemes/create-divi-extension#295]
Hi, i'm new for developing custom module and i have a question about the 'upload-gallery' field type.
How i can get each images url in the php render function for puting them in img src ?

**Comment by xxtesaxx** [comment]
The upload gallery will give you a comma separated list of attachment IDs. You can use WordPress core functions to retrieve the src or even better the srcset by a given attachment ID. So you basically first split the string by comma into an array, then iterate over each id and retrieve the attachment by id.
