### ISSUE TITLE
Retrieve styles in vb when injecting layouts with shortcode

### ISSUE THREAD

**Issue by wassy83** [elegantthemes/create-divi-extension#301]
### Problem Description
I'm using `<?php echo do_shortcode('[et_pb_section global_module="LAYOUT_ID"][/et_pb_section]');?>` to inject some layouts in single_cpt.php pages, I don't want to use the new theme builder cause php gives to me more flexibility, This is working good but, when enabling visual builder, the injected sections/layouts are missing their styles and looks completely different, so my customers are a litlle confused. Is there a way to fix this now that theme builder is released?

### Steps To Reproduce
1.insert this code `<?php echo do_shortcode('[et_pb_section global_module="LAYOUT_ID"][/et_pb_section]');?>` into the php of your pages.
2.frontend is showing good.
3.visual builder is missing the related styles.

many thanks

**Comment by lots0logs** [comment]
Sorry for the delayed response. The visual builder generates the styles for its layouts on the fly. You would have to do the same in this case. Most likely method would be to use AJAX to get the styles from the server right when the page loads. Though to be clear, we cannot official support this functionality nor guarantee that it will always work like it does today.
