### ISSUE TITLE
Multiple tiny_mce in the same module

### ISSUE THREAD

**Issue by cfv55** [elegantthemes/create-divi-extension#302]
I need to have more than one tiny_mce in the same module.

When I add many attributes with this type, only one attribute works correctly if it is called "content".

For example:
// It doesn't work 
'rich_text' => array(
                'label' => esc_html__('Text *', 'evr'),
                'type'            => 'tiny_mce',
                'option_category' => 'basic_option',
                'description' => esc_html__('Text', 'evr'),
            ),
// It works
'content' => array(
                'label' => esc_html__('Text *', 'evr'),
                'type'            => 'tiny_mce',
                'option_category' => 'basic_option',
                'description' => esc_html__('Text', 'evr'),
            ),
// It doesn't work 
'description' => array(
                'label' => esc_html__('Body', 'evr'),
                'type'            => 'tiny_mce',
                'option_category' => 'basic_option',
                'description' => esc_html__('Body', 'evr'),
            ),
...

When I use any attribute different than 'content' if I add a link with target blank it isn't saved well in database and its value is not recovered. 

For example in the tyny_mce I have:` asdfdsf <a href="https://www.elegantthemes.com/gallery/divi/" target="_blank" rel="noopener noreferrer" title="sds">link</a>`
In database I have:
`rich_text="<p>asdfdsf <a href=%22https://www.elegantthemes.com/gallery/divi/%22 target=%22_blank%22 rel="%22noopener noopener noreferrer" noreferrer%22 title=%22sds%22>link</a></p>"
`

**Comment by lots0logs** [comment]
This should be fixed in the latest version. If you still have trouble we can reopen the issue.
