### ISSUE TITLE
NPM start Cannot GET /

### ISSUE THREAD

**Issue by chozze** [elegantthemes/create-divi-extension#303]
### Problem Description
localhost:3000 shows only Cannot GET / after running npm start

### Steps To Reproduce
cd .../wp-content/plugins
npx create-divi-extension my-extension
cd my-extension
npm start

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/11600606/68528495-afebdc00-02f3-11ea-9d20-0365f3b32352.png)

**Comment by chozze** [comment]
Right, I've just figure it out I need to run my custom web server ..jeez my bad!

**Comment by daniesy** [comment]
Hey @chozze, i'm getting the same error, but i already have my custom web server on. Any hints?

**Comment by daniesy** [comment]
@chozze i've got the same error. How did you fix it? I have my custom web server running in docker.

**Comment by chozze** [comment]
Actually you just need to run both together - npm/yarn to build React part together with web server to build php/wordpress files.

Simply access localhost/wp-admin and it will work just fine.

Ales
