### ISSUE TITLE
Render and return the content of Global Header from Theme Builder.

### ISSUE THREAD

**Issue by cmsbased** [elegantthemes/create-divi-extension#304]
### Problem Description
Is it possible to render and return content of "Global Header" or "Global Footer" from "Theme Builder"? Example use is WP REST API endpoint with header/footer content of the front end website.

**Comment by lots0logs** [comment]
Sorry for the delayed response. I'm afraid that's not something the code officially supports. There's a chance that you could get it to do what you want but there's no guarantee it would continue to work in the future.
