### ISSUE TITLE
Is it possible to disable module settings?

### ISSUE THREAD

**Issue by bholaday** [elegantthemes/create-divi-extension#338]
### Problem Description
I have a custom module for which I'd like to disable all settings. I want it to be completely hardcoded (because I don't want a client to be able to change anything about it). Is there a way to do that? I've created the custom module, but I'd like to get rid of the settings modal.

### Screenshot and/or gif

I want to get rid of this whole modal
![Image of Custom Module Settings modal](https://snipboard.io/eqnUr0.jpg)

**Comment by lanresmith** [comment]
sorry @bholaday, this is not possible currently.

**Comment by bholaday** [comment]
Thanks for the reply.
