### ISSUE TITLE
Installing Divi theme as a Composer package

### ISSUE THREAD

**Issue by szepeviktor** [elegantthemes/create-divi-extension#351]
Hello!
I'm trying to develop a Composer plugin that facilitates

```bash
composer require elegantthemes/divi
```

using ET's **update** API endpoint: `https://www.elegantthemes.com/api/api.php`

Could you support me or should I r3verse engineer Divi theme to learn how that API works?

My recent Composer plugin is for installing Envato themes (e.g. `Avada`) and plugins simply as Composer packages: https://packagist.org/packages/szepeviktor/composer-envato

**Comment by tamerziady** [comment]
Were you ever successful at this. I am looking for a way to install DIVI via composer?

**Comment by szepeviktor** [comment]
Hello Tamer!
This is all I have https://github.com/ffraenz/private-composer-installer/issues/47
