### ISSUE TITLE
Filters advanced field. CSS is not being applied correctly

### ISSUE THREAD

**Issue by jcdotnet** [elegantthemes/create-divi-extension#358]
### Problem Description

I'm using the advanced filed `Filters` and it's working perfectly when the CSS is applied to the main selector. However, it is not applied for custom selectors.

### Steps To Reproduce

1) I have added the filters settings to the advanced fields array:

```
'filters' => array (
	'css' => array(
	    'main' => '%%order_class%% .my-selector',
	    'hover' => '%%order_class%% .my-selector',
	), 
),
```
2) The CSS is applied to `%%order_class%%`, not to the `%%order_class%% .my-selector` 

How can I style only `%%order_class%% .my-selector`?

TIA

**Comment by alexhooley** [comment]
I've found sometimes main_css_element works better than %%order_class%% but I'm not sure why.

`public function init()
{
  $this->name = esc_html__('My Extension', 'myex-my-extension');
  $this->slug = "myex_my_module";
  $this->main_css_element = "%%order_class%%";
}
'filters' => array (
	'css' => array(
	    'main' => "{$this->main_css_element} .my_selector",
	    'hover' => "{$this->main_css_element} .my_selector",
	), 
)`

**Comment by jcdotnet** [comment]
Thank you, @alexhooley. It doesn't work either with the prop. 

It seems like the Filters CSS is only applied to the main element. Can anyone confirm this?

**Comment by IvanChiurcci** [comment]
> It seems like the Filters CSS is only applied to the main element. Can anyone confirm this?

Yes, I noticed the same issue. Custom selector works in VB but on front-end is applied to main element only. Tried to use the "child_filters_target" but didn't work for me either, so, I had to give up on my idea.

**Comment by jcdotnet** [comment]
Thanks @IvanChiurcci. 

I'm closing the issue. If someone finds a solution, please reopen and share!
