### ISSUE TITLE
Icons not rendering correctly in the visual builder.

### ISSUE THREAD

**Issue by kannan6240** [elegantthemes/create-divi-extension#368]
The visual builder displays multiple incorrect icons. The preview is all correct and the icons are displayed properly. See I'm doing something wrong or is this a bug.

JSX code
```
render() {
  return (
          <div className={'card'}>
              <span className={'et-pb-icon ' + 'card__infoicon'}>
                  {this.props.font_icon}
              </span>
              <h1 className={this.props.card__title}>This is a title</h1>
          </div>
);
```

PHP Code
```
public function render( $unprocessed_props, $content = null, $render_slug ) {
		return sprintf( '
                      <div class="card" >
                          <span class="et-pb-icon card__infoicon">
                              %1$s
                          </span>
                          <h1 class="card__title">This is a title</h1>
                      </div>
                  ', 
                      esc_attr( et_pb_process_font_icon( $this->props['font_icon'] ) ),
                      $this->props['content'],
                  );
```

### Screenshot and/or gif
**Previewing the site**
![image](https://user-images.githubusercontent.com/26121609/84139883-51940100-aa6e-11ea-9dd6-9c1a4bf63412.png)

**With Visual Builder Enabled**
![image](https://user-images.githubusercontent.com/26121609/84140346-1514d500-aa6f-11ea-928f-77c203518e41.png)

How can I fix this issue?

**Comment by alexwbrinkman** [comment]
What icon are you trying to display? Divi icons tend to be generated in one of 2 ways: either by placing the icon unicode in the body of the element (such as in the instance of the blurb module) or by placing the icon unicode in the data-icon attribute.

The class ```et-pb-icon``` says:
```
.et-pb-icon {
    font-family: ETmodules;
    content: attr(data-icon);
    ...
}
```

so it's telling the element to use the ETmodules font family and that the content of the element should come from the data-icon attribute.

What does the class ```card__infoicon``` do?

**Comment by kannan6240** [comment]
The class `card__infoicon` is as below
```
.card__infoicon {
    position: absolute;
    top: 10px;
    right: 28px;
    font-size: 1.4em;
    color: #000000;
    transition: ease-out 0.3s;
}
```

When working with Visual Builder I want the icon to appear correctly, I'm not bothered how it generates.

Thank you. @alexwbrinkman

**Comment by alexwbrinkman** [comment]
Ok. I also misspoke, ```et-pb-icon``` can work without the data-attribute as in the case of the blurb module.

In JSX you also need to process the icon - try the following:

```window.ET_Builder.API.Utils.processFontIcon( this.props.font_icon )```

**Comment by kannan6240** [comment]
Tried placing it. But just check the entire code below, 

```
// External Dependencies
import React, { Component } from 'react';

// Internal Dependencies
import './style.css';

class InfoBox extends Component {
    static slug = 'nemo_info_box';

    window.ET_Builder.API.Utils.processFontIcon(this.props.font_icon);
    
    render() {
        const Content = this.props.content;

        return (

            <div className={'card'} tabindex="0">
                <span className={'et-pb-icon ' + 'card__infoicon'}>
                    {this.props.font_icon}
                </span>
                <h1 className={this.props.card__title}>This is a title</h1>
            </div>
        );
    }
}

export default InfoBox;
```
It did not work. Please let me know if I did anything wrong.

**Comment by kannan6240** [comment]
Oops. My mistake.

I did not place it correctly. 


```
// External Dependencies
import React, { Component } from 'react';

// Internal Dependencies
import './style.css';

class InfoBox extends Component {
    static slug = 'nemo_info_box';

   render() {
        const Content = this.props.content;

        return (

            <div className={'card'} tabindex="0">
                <span className={'et-pb-icon ' + 'card__infoicon'}>
                    {window.ET_Builder.API.Utils.processFontIcon(this.props.font_icon);}
                </span>
                <h1 className={this.props.card__title}>This is a title</h1>
            </div>
        );
    }
}

export default InfoBox;
```


**It worked.**
Thank you @alexwbrinkman
