### ISSUE TITLE
Minify And Combine Javascript Files

### ISSUE THREAD

**Issue by charles890123** [elegantthemes/create-divi-extension#373]
### Problem Description
All our extensions appear to have a conflict with the Minify And Combine Javascript Files option on the Divi Theme Options page. If disabled and any of our extensions is active, we are seeing the following message:

**Divi uses uncombined and unminified javascript files because "SCRIPT_DEBUG" constant on wp-config.php has been set to "true". Other plugin can enforce Divi to use uncombined and unminified javascript files by filtering "et_load_unminified_scripts" filter as well.**

We are not using the et_load_unminified_scripts filter anywhere in our extensions. I also test with the example Divi modules extension and was able to replicate the issue.

### Steps To Reproduce
1. On Divi latest version 4.4.8, no child theme active, latest WP 5.4.2, and only the extension https://github.com/elegantthemes/divi-extension-example active.
2. Deactivate the option Minify And Combine Javascript Files and save.

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/16024719/85137081-9f4aff00-b20e-11ea-8cb7-296dd82025b4.png)

**Comment by alexhooley** [comment]
This warning goes away when I create the production version with `yarn zip` and install that version.

**Comment by VladET** [comment]
I opened an issue in our main Divi repository so I'm going to close this one.
