### ISSUE TITLE
How to set default values in sortable list or options list?

### ISSUE THREAD

**Issue by khurana-ankur** [elegantthemes/create-divi-extension#395]
### Problem Description
I want the sortable list or option list to be pre-filled with some default values, but I can't able to do that. I don't know the exact way to pass the default values in this field type. I tried using array but it throws an error.

### Steps To Reproduce
1.
$fields['checkbox_options'] = array(
				'label'           => esc_html__( 'Options', 'et_builder' ),
				'type'            => 'sortable_list',
				'checkbox'        => true,
				'option_category' => 'basic_option',
				'toggle_slug'     => 'field_options',
				'right_actions'   => 'move|link|copy|delete',
			);
Like this is the field, and i want to add a default list in it. I tried using arrays, string in the 'default' index of this array but can't able to get the default list.

**Comment by khurana-ankur** [comment]
I tried using json encode and it worked.

**Comment by jcdotnet** [comment]
Hi @khurana-ankur, I have encoded the array but the fields are not editable (they are readonly and you can't type).

This is my default array: 
`$defaults = array(array('List Item 1'), array('List Item 2')); `

And my default value:
`'default'  => json_encode($defaults),`

Seems like something is wrong, can you help me out here? TIA

**Comment by jcdotnet** [comment]
Never mind. I will handle the values in the render function.
