### ISSUE TITLE
Trigger change on Divi editor when changing page settings value

### ISSUE THREAD

**Issue by alvarotrigo** [elegantthemes/create-divi-extension#405]
I'm looking for a way to detect a change on the page/post settings values and change parts of the front-end Divi builder by using JavaScript.

Basically I want to add a class to the body (or any other element) when a specific page setting is enabled. This way I am able to modify how certain elements look on the editor so developers aren't forced to click on "preview" in order to see how their website will end up looking.

I was not able to find any events or callbacks triggered by Divi to achieve this, so I'm a bit lost in here. Is there any way to achieve this?

![image](https://user-images.githubusercontent.com/1706326/93214238-328bc600-f765-11ea-9b68-1a34c4c7fbe3.png)

**Comment by poxtron** [comment]
We've included a new WP JS filter to address this, it should be merged soon. I will let you know when it will be available.

**Comment by alvarotrigo** [comment]
@poxtron awesome! 🙏 I appreciate the fast movement from your side!
If you can notify me on when it gets released that'd be great! 👍

**Comment by ayubadiputra** [comment]
@alvarotrigo It's merged and will be available on the upcoming Divi Builder update.

**Comment by alvarotrigo** [comment]
Awesome! 
Could you notify me when the new version is released?

Or can I get it directly from somewhere else?
