### ISSUE TITLE
We are creating Divi Custom Module and Need help regarding load my shortcode data

### ISSUE THREAD

**Issue by divyang19** [elegantthemes/create-divi-extension#412]
### Problem Description
We have set up everything and module works fine with divi but 1 problem is that, We can't load my other plugin shortcode html while render so can you please give me a appropriate example while load shortcode and get render in JSX file. 

### Steps To Reproduce
1.
When Load module and when we select form and pass that parameter in JSX file and render out put but that output just get text or string but not work shortcode data so we need to find out how divi module work while load shortcode and get the data from there.

We follow below code :

https://www.elegantthemes.com/documentation/developers/divi-module/how-to-create-a-divi-builder-module/

**Comment by divyang19** [comment]
Hi  lanresmith, How are you?

**Comment by lanresmith** [comment]
Hi @divyang19 ! I'm fine. Hope you're too :)
Do you mean that you tried to use a shortcode while rendering output in the `render` method of your module's PHP class?

**Comment by divyang19** [comment]
Yeah correct

**Comment by divyang19** [comment]
I am trying to render Booking form using shortcode and with some args so i can add as parameter in module and show output but while i am used that output nothing just getting blank so can you please give me a example in jsx file while using shortcode so its good for me.

**Comment by divyang19** [comment]
Neverminded I have fixed that issue and working fine.

Thanks for your efforts .

Have a great day ahead Olanrewaju Smith

**Comment by lanresmith** [comment]
@divyang19 maybe this is what you want?

register your shortcode **early** (maybe in your extension's main file in the extension's root folder):

```
add_shortcode( 'booking', 'my_shortcode' );
function my_shortcode( $atts ) {
	// careful with 'extract' though, be sure you understand implications
	extract( shortcode_atts( array(
		'type' => '' /* used in the shortcode tag like so: [booking type="..."] */
	), $atts ) );
	return
		'<form>' .
			'<input type="email" /> ' .
			'<input type="text" value="' . $type .'" />' .
		'</form>';
}
```

Then, somewhere in the render method of the module's `jsx` file:

```
<BookingForm {...this.props} />
```

while this is BookingForm.jsx:

```
import React from 'react';

function BookingForm(props) {
  return (
    <form>
      <input type="email" />{' '}
      <input type="text" value={props.booking_type} />
    </form>
  );
}

export default BookingForm;
```

and finally, in the `render` method of the module's PHP class:

```
$form = do_shortcode(
			sprintf( '[booking type="%s"]', sanitize_text_field( $this->props['booking_type'] ) )
		);

return sprintf(
			'<h2 class="heading-class">%1$s</h2>
			<div>%2$s</div>
			<div>%3$s</div>',
			esc_html( $this->props['heading'] ),
			$this->props['content'],
			$form
		);
```

**Comment by divyang19** [comment]
Thanks for your support.

Have a great day ahead

**Comment by deeprojects** [comment]
> Neverminded I have fixed that issue and working fine.
> 
> Thanks for your efforts .
> 
> Have a great day ahead Olanrewaju Smith

Hi divyang19,

Im interested in your Solution. Can you send me the Code?
