### ISSUE TITLE
[Question] What is the minimal code needed to add a custom module

### ISSUE THREAD

**Issue by Tymotey** [elegantthemes/create-divi-extension#415]
So far I did this: https://www.screencast.com/t/R8YBnjEDAG
Is ok, I can add more customizations, BUT the problem I have is the preview of rendered code: on admin I see this: https://www.screencast.com/t/R8YBnjEDAG  But the output is a result of do_shortcode.
How can that be added to my code?

**Comment by Tymotey** [comment]
Basically How can I make it compatible with React

**Comment by Tymotey** [comment]
[DIVI.zip](https://github.com/elegantthemes/create-divi-extension/files/5467524/DIVI.zip)
Here it is

**Comment by Tymotey** [comment]
ahhhhh. I jsut realized that in first post I added a wrong first screenshot. sorry!

**Comment by code-with-mehedi** [comment]
Hello @Tymotey ,
Running the command creates a plugin that comes with a pre-build "Hello World" module, so technically you need no minimal code.
Some references:
setup: https://www.elegantthemes.com/documentation/developers/create-divi-extension/
development: https://www.elegantthemes.com/documentation/developers/how-to-create-a-divi-builder-module/
Thanks

**Comment by Tymotey** [comment]
Ok. I understand that. What I want is minimal code, I don't want all the
folder structure, just the way to show the correct preview in admin

**Comment by code-with-mehedi** [comment]
Hello @Tymotey,
The fact is here that the module is build based on react js so while your developing you need those node js module and packages for react js. When development is done then build the production version where there will be no development purpose code. Hope you understand.
Thanks

**Comment by Tymotey** [comment]
Are there some wp actions and js files that are needed to be implemented?

Thank you for your time!

**Comment by Tymotey** [comment]
I am thinking at Gutenberg or Elementor or VC from WPBakery that has some
clear classes to extend, hooks to add OR even JS to write for developer to
add a custom block.
Gutenberg is based on React too

**Comment by ayubadiputra** [comment]
@Tymotey The extension structure generated by Create Divi Extension is already minimalist and mandatory to have for some reasons. Here the minimum structure to create a custom module and why we need it:

```
├── includes -> The app source directory. All the React components and loader files should be located here.
│   ├── MyApp.php -> This file contains a class that extends DiviExtension main class to initiate your custom extension.
│   ├── loader.js -> React components loader, should be located inside `includes` directory.
│   ├── loader.php -> PHP modules loader. You can ignore this field and include your custom modules files manually by overriding `hook_et_builder_modules_loaded` method on your main extension class.
│   └── modules -> The modules source directory. All the React modules files should be located here.
│       ├── HelloWorld
│       │   ├── HelloWorld.jsx
│       │   ├── HelloWorld.php
│       │   └── style.css
│       └── index.js
├── my-app.php -> Main plugin file. It can be adapted based on your need.
├── package.json -> The app packages to build the extension.
├── scripts -> The app scripts directory. All the scripts will be processed and added here. The main extension class will load all your extension scripts from this directory.
│   ├── builder-bundle.min.js
│   ├── frontend-bundle.min.js
│   └── frontend.js
└── styles -> The app styles directory. All the styles will be processed and added here. The main extension class will load all your extension styles from this directory.
    ├── backend-style.min.css
    ├── style-dbp.min.css
    └── style.min.css
```

And here the plugin that implement the structure above [my-app.zip](https://github.com/elegantthemes/create-divi-extension/files/5489400/my-app.zip).

**Comment by Tymotey** [comment]
Thank you for the answer. I will look into it.
