### ISSUE TITLE
Question about gitignore

### ISSUE THREAD

**Issue by jeromeheissler** [elegantthemes/create-divi-extension#424]
Default gitignore contains : 
```
/scripts/bundle.min.js
/styles/bundle.min.css
```

but when i'm running `yarn build` it produce files : 
```
scripts/builder-bundle.min.js
scripts/frontend-bundle.min.js
styles/backend-style.min.css
styles/style-dbp.min.css
styles/style.min.css
```

the gitignore should not ignore all .min.css and .min.js files ?

____
### Attached PR
* https://github.com/elegantthemes/create-divi-extension/pull/428

**Comment by hrrarya** [comment]
If you don't want to push minified files on Github, then simply include them in .gitignore.

**Comment by lanresmith** [comment]
@jeromeheissler you can include those ones too in the gitignore file. The repo will also be updated to include them too.
