### ISSUE TITLE
Rerender the child styles (React)

### ISSUE THREAD

**Issue by jcdotnet** [elegantthemes/create-divi-extension#431]
Hi everyone, especially the ET staff. Could you kindly help me out on this issue?

### Problem Description
I have a child component that renders the CSS that I have added to the static method css(props) into a style tag inside the child module output.

Inside the css method I use the prop.element_width to style the element width. So far so good.

That prop is updated when the element is loaded by following this approach: when the element is loaded an event is triggered, the event handler passes the updated props to the parent and the parent is rendered again. This does not update the child output.

However, when I mouse over the container section, the child module renders correctly. 

Any help here is really appreciated since I don't manage to rerender the child module style, thank you!

**Comment by lanresmith** [comment]
@jcdotnet could you please show some code?

**Comment by jcdotnet** [comment]
@lanresmith, sure!
I just created a pretty basic module so you can see the problem. I'm almost there, I feel like I'm overcomplicating this, though.
Repo:
https://github.com/jcdotnet/divi-extension-image-load

**Comment by lanresmith** [comment]
@jcdotnet could you please check out the PR I sent to the repo above?

If you check the browser console, you'll see the following error msg:
```
Uncaught TypeError: Cannot add property image_width, object is not extensible
    at ImageLoadItem._onImgLoad (ImageLoadItem.jsx:26)
```

In react, a component should not update its own props(having a component update its own props even if possible is an anti-pattern), but can update its state and the props of its children.

After the changes I made, upon saving in the settings modal (by clicking the check mark button by the bottom right corner) gives the desired result - the `<p>Image Width (px): { this.props.image_width }</p>` part is updated in the UI.

Please do let me know if there are other issues.

**Comment by jcdotnet** [comment]
@lanresmith thank you for the PR and sorry for not checking this.props.content (I created the example very quickly)

Yeah, you are right, but I'm still having the same issue: when loading the page the child module is not updated. Please check (save the page and reload it, instead of saving in the settings modal).

This is important because the VB page preview will be different from the front-end page until the user hovers over the container section, and this way, I can't even think of including this behavior in one of my plugins.

We are almost there...

**Comment by jcdotnet** [comment]
The child needs to be updated again, so I'm changing the key only if we haven't passed the image width yet (ImageLoad.jsx, line 12):

```
_updateParent(childProps) {
    this.props.content.forEach( (elem, i) => {
      if (i === childProps.moduleInfo.order && elem.props.attrs.image_width !== childProps.image_width) { // ADDED CONDITION
        elem.key = Math.random(); // changing the key renders the child and the issue is solved // ADDED
        elem.props.attrs.image_width = childProps.image_width;
      }
    });
    this.forceUpdate(); // we actually change the component state, we are just forcing the update for testing purposes
  }
```
Even though this solves the issue, I don't like this solution at all. Also, I'm overriding the key value set by Divi:
`deil_image_load_item-0.0.0.0-0`

@lanresmith How would you update the child at this point in a "React and Divi" way? Thanks.
