### ISSUE TITLE
A function to render raw DIVI content with DIVI shortcodes into HTML

### ISSUE THREAD

**Issue by Lovor01** [elegantthemes/create-divi-extension#432]
### Problem Description
I am looking for a function to transform raw DIVI content into HTML for output into page. 
I need that for popup, which I am building, and which grabs content from various custom posts via AJAX.

**Comment by lanresmith** [comment]
@Lovor01 you're probably looking for [`do_shortcode`](https://developer.wordpress.org/reference/functions/do_shortcode/)

**Comment by Lovor01** [comment]
> 
> 
> @Lovor01 you're probably looking for [`do_shortcode`](https://developer.wordpress.org/reference/functions/do_shortcode/)

No, do_shortcode() does not work. Content is pulled from another post via get_the_content() function. I also tried et_builder_render_layout() which I found in divi code, but with same results.

**Comment by Lovor01** [comment]
> 
> 
> @Lovor01 you're probably looking for [`do_shortcode`](https://developer.wordpress.org/reference/functions/do_shortcode/)

After further testing, it seems that `do_shortcode` does not work in AJAX action wp_ajax_nopriv_get_post. Any ideas how to fix this?

**Comment by Lovor01** [comment]
On yet further testing I discovered that `et_builder_render_layout` (and `do_shortcode`) are not working properly in AJAX response in PHP. Perhaps not everything is loaded? Can you help me with this?

**Comment by Lovor01** [comment]
I think I know now what exactly is the problem. Admin-ajax.php is technically admin part of the wordpress and DIVI won't resolve shortcodes in admin. Can you give me workaround for this?

**Comment by lanresmith** [comment]
@Lovor01 could you please try as suggested here: https://wordpress.stackexchange.com/a/53491 ?

**Comment by Lovor01** [comment]
> 
> 
> @Lovor01 could you please try as suggested here: https://wordpress.stackexchange.com/a/53491 ?

Proposed solution works just the same as with ajax-admin.php. Obviously, the part of divi responsible for resolving builder shortcodes to HTML is not yet loaded or active. Can you refer me to proper solution, I am running out of time?

**Comment by Lovor01** [comment]
I found solution by referring to issue #128 and by inspecting the DIVI code in framework.php file.
DIVI expects a list of allowed AJAX actions to load builder, and my action must be added to list my means of appropriate filter ( I changed code in #128 to be futureproof):
```
add_filter( 'et_builder_load_requests', function( $builder_load_requests ) {
	$builder_load_requests['action'][] = 'ajax_get_post';
	return $builder_load_requests;
} );
```
where ajax_get_post is my AJAX action. I also use `et_builder_render_layout()` instead of `do_shortcode()` because it is faster. I hope this helps all developers with same issue.

**Comment by desmondshowell** [comment]
I have this same issue. @Lovor01, can you please post your full code?

**Comment by desmondshowell** [comment]
@Lovor01, nevermind. I found the thread in issue #128.

Here is my code for future seekers.

Change "get_ajax_posts" to your function name.

```
add_filter( 'et_builder_load_requests', function( $builder_load_requests ) {
    $builder_load_requests['action'][] = 'get_ajax_posts';
    
    return $builder_load_requests;
});
```

**Comment by elsalweb** [comment]
Hello @desmondshowell , 

I try your code but it doesn't work. Can you please help me please ?

`
add_filter( 'et_builder_load_requests', function( $builder_load_requests ) {
    $builder_load_requests['action'][] = 'temoignages_query';
    return $builder_load_requests;
});

function temoignages_query() {
    $ids = "5653";
    $return = '[et_pb_blog_extras post_type="temoignage" posts_number="100" featured_image_size="full" use_overlay="on" overlay_icon_color="RGBA(255,255,255,0)" hover_overlay_color="RGBA(255,255,255,0)" use_read_more_button="on" read_more_text="Voir son histoire" show_author="off" show_date="off" show_categories="off" show_comments="off" content_color="#000000" _builder_version="4.14.9" _module_preset="default" header_font="Poppins|900|||||||" header_text_align="right" header_text_color="#000000" header_font_size="50px" body_font="Poppins|700|||||||" body_text_align="right" body_text_color="#000000" body_font_size="24px" body_link_font="Poppins|300|||||||" body_link_text_color="#E83E1B" body_link_font_size="18px" meta_text_align="left" background_color="RGBA(255,255,255,0)" custom_read_more="on" read_more_text_size="18px" read_more_text_color="#E83E1B" read_more_font="Poppins||||||||" read_more_icon="&#x24;||divi||400" read_more_on_hover="off" read_more_alignment="right" z_index="49" custom_padding="|14%||14%|true|true" hover_enabled="0" global_colors_info="{}" read_more_bg_color__hover_enabled="on|hover" read_more_bg_color__hover="RGBA(255,255,255,0)" read_more_bg_enable_color__hover="on" read_more_text_color__hover_enabled="on|hover" read_more_text_color__hover="rgba(232,62,27,0.8)" background__hover_enabled="on|hover" background_color__hover="RGBA(255,255,255,0)" background_enable_color__hover="on" no_results_text="Aucun témoignage ne correspond, veuillez réinitialisez les filtres." sticky_enabled="0"][/et_pb_blog_extras]';
    echo do_shortcode($return);
	wp_die();
}

add_action( 'wp_ajax_load_temoignages', 'temoignages_query' );
add_action( 'wp_ajax_nopriv_load_temoignages', 'temoignages_query' );`

Thank you very much !
