### ISSUE TITLE
Docker PHP Settings

### ISSUE THREAD

**Issue by holmesadrianh** [elegantthemes/create-divi-extension#435]
I cannot find any documentation to edit the settings for the php running in the docker container for the development environment. Can anyone point me in the right direction? I would like to edit the php.ini. I need to increase some memory and times.

Any help is appreciated!

**Comment by lanresmith** [comment]
Hi @holmesadrianh sorry this is out of the scope of CDE. Could you please google e.g. "docker wordpress edit php.ini"?

**Comment by holmesadrianh** [comment]
Thanks for the feedback. Will have a look.
