### ISSUE TITLE
Passing a module field value to a module field definition

### ISSUE THREAD

**Issue by jcdotnet** [elegantthemes/create-divi-extension#436]
Hi everyone, I have searched for similar issues and the ones I have found don't solve mine.

Basically I need to get the value from a field and use that value in another one. I can get the values once the module is being rendered, but I need those values in the field definition, so that they can be used in the VB settings modal.

This is very useful when creating custom fields. That way, we can display custom data the user has entered before and not make them to enter the same data again.

For example, we may have this select field: 
 ```
'display' => array(
		'label'     	=> esc_html__( 'Display', 'et_builder' ),
		'type'        	=> 'select',
		'options'	=> array('square', '4:3', '16:9', 'original'),
		'default'  	=> 'original',
),
```
 and a custom field that uses the display value entered by the user:
```
'image_display' => array(
	'label'     		=> esc_html__( 'Display', 'et_builder' ),
	'type'        	=> 'deil_input',
	'deil_placeholder'	=> 'original', // here I want to pass to the custom field the value entered in the parent display field rather than the original string
),
```
For this example we're displaying the select value as the input placeholder:
```
render() {
    return(
      <input
        id={`deil-input-${this.props.name}`}
        name={this.props.name}
        value={this.props.value}
        type='text'
        className='deil-input'
        onChange={this._onChange}
        placeholder={this.props.fieldDefinition.deil_placeholder}
      />
    );
```
Divi uses the parentModule prefix to set the field visibility based on a parent field value, so I hope we can somehow get the field values to use them in other module fields definition. 

You can look at the example code here:
https://github.com/jcdotnet/divi-extension-image-load 

PR/suggestions are welcome :)

Thank you in advance

**Comment by jcdotnet** [comment]
@lanresmith @code-with-mehedi @VladET @xxtesaxx @lots0logs can you give me some direction here? Thank you!

**Comment by ayubadiputra** [comment]
Hi @jcdotnet,

> Basically I need to get the value from a field and use that value in another one. I can get the values once the module is being rendered, but I need those values in the field definition, so that they can be used in the VB settings modal.

I don't think this is good idea since there will be double reload when field definition is updated with dynamic value as you mentioned above. 

Am I correct that you want to access/use other setting values on custom field React component? In that case, you can take a look `this.props.moduleSettings` where all setting values for the current module passed to custom field component.

> Divi uses the parentModule prefix to set the field visibility based on a parent field value, so I hope we can somehow get the field values to use them in other module fields definition.

However, there is no way yet to get parent module setting values at this moment. I already added this on our backlog to pass parent module attributes for the custom field that is being used by the child module.

**Comment by jcdotnet** [comment]
Thank you @ayubadiputra 

> However, there is no way yet to get parent module setting values at this moment. I already added this on our backlog to pass parent module attributes for the custom field that is being used by the child module.

That's exactly what I need. Please let us know when we can access those parent setting values from the child custom field.

**Comment by jcdotnet** [comment]
Hi, I just want to let you know that this can be done by using the et.builder.store.setting.update JS hook (we first need to save the module fields values in a variable and them use them in the custom field).

**Comment by ayubadiputra** [comment]
@jcdotnet Glad to know, you can use that hook to give alternative workaround. Actually, the request you asked above is currently under review.

**Comment by ayubadiputra** [comment]
@jcdotnet It has been long time, but I just want to inform you that it's now possible to access parent module values via `parentModuleSettings`.
