### ISSUE TITLE
Modules gone  after build and zip

### ISSUE THREAD

**Issue by alexvibealex** [elegantthemes/create-divi-extension#437]
Hi , we are developing custom modules using create divi extension , 
### Problem Description
Really easy method to register our modules , 
It was working fine when we were developing but since build modules are not showing in the divi builder , I also npm run zip it and install it but it didn't work . All folders are there in the module but its simply not showing any modules after build .

### Steps To Reproduce
1. npm run build on terminal 
2. then modules are not loading in divi builder .

please share if i missed something?

**Comment by alexvibealex** [comment]
I just checked the build code and found that there is no code to enqueue the scripts : " builder-bundle.min.js " and " frontend-bundle.min.js ". Is it done by then divi builder plugin ?

**Comment by lanresmith** [comment]
Hi @alexvibealex this looks strange. Could you please confirm from wp admin that the extension is still activated? And please check your browser console for errors. There is definitely code to enqueue those scripts; kindly see the functions `_enqueue_bundles` & `_enqueue_debug_bundles` (for build & dev respectively) in `includes/builder/api/DiviExtension.php` in the `Divi` theme folder.

**Comment by alexvibealex** [comment]
Im sorry for all this , It was my mistake in plugins initialisation function.Please close this or even delete it .
