### ISSUE TITLE
Create extension fails on windows

### ISSUE THREAD

**Issue by MitchellWT** [elegantthemes/create-divi-extension#445]
### Problem Description
"npx create-divi-extension my-extension" script fails on windows machine.

### Steps To Reproduce
1. Be on windows machine.
2. Perform npx command in powershell.

### Screenshot and/or gif
Here is the output from the debug logs:

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'create-divi-extension',
0 verbose cli   'my-extension'
0 verbose cli ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\Users\Satel\Documents\divi-extension\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\Satel\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\Satel\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 verbose npm-session 9067013c64423d92
20 timing npm:load Completed in 24ms
21 http fetch GET 304 https://registry.npmjs.org/create-divi-extension 174ms (from cache)
22 timing arborist:ctor Completed in 1ms
23 timing arborist:ctor Completed in 0ms
24 timing arborist:ctor Completed in 0ms
25 timing command:exec Completed in 88622ms
26 verbose stack Error: command failed
26 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
26 verbose stack     at ChildProcess.emit (node:events:376:20)
26 verbose stack     at maybeClose (node:internal/child_process:1055:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
27 verbose cwd C:\Users\Satel\Documents\divi-extension
28 verbose Windows_NT 10.0.19041
29 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "exec" "--" "create-divi-extension" "my-extension"
30 verbose node v15.3.0
31 verbose npm  v7.0.14
32 error code 1
33 error path C:\Users\Satel\Documents\divi-extension
34 error command failed
35 error command C:\Windows\system32\cmd.exe /d /s /c create-divi-extension my-extension
36 verbose exit 1

**Comment by code-with-mehedi** [comment]
@MitchellWT, Do you still need assistance with this issue?

**Comment by MitchellWT** [comment]
Nah bro, moved to linux.
