### ISSUE TITLE
Overwrite function "et_builder_get_the_term_list"

### ISSUE THREAD

**Issue by im8hoursahead** [elegantthemes/create-divi-extension#446]
### Problem Description
Hi there.
I need some help with a very specific technical question involving the overriding of a function.

The function I'd like to overwrite is:

"et_builder_get_the_term_list"

But it doesn't have the "if !exists" check before it... so I can't override it in my own functions.php easily...

Anyone can help me out? thanks x

### Steps To Reproduce
1.

**Comment by lanresmith** [comment]
Hi @im8hoursahead! You're right that the function isn't overridable, but there is a hook you can use, pls see `get_the_term_list()` and the filter:
	```
/**
	 * Filters the term links for a given taxonomy.
	 *
	 * The dynamic portion of the filter name, `$taxonomy`, refers
	 * to the taxonomy slug.
	 *
	 * @since 2.5.0
	 *
	 * @param string[] $links An array of term links.
	 */
	$term_links = apply_filters( "term_links-{$taxonomy}", $links );
```

And, with that, see if that helps you accomplish what you are looking to do. Let me know if you have any further questions.

**Comment by im8hoursahead** [comment]
Hi Olanrewaju,

Thanks so much! It did work :)

Anna
*Anna M.*
*Founder - I'M 8 HOURS AHEAD*
*E*: im8hoursahead@gmail.com
*W:* *https://im8hoursahead.com <https://im8hoursahead.com>*
