### ISSUE TITLE
Only activate Divi Builder on certain pages of CPT

### ISSUE THREAD

**Issue by cxlxin** [elegantthemes/create-divi-extension#464]
### Problem Description
We use Divi and would like to only use the Divi Builder for specific posts of our custom post type.

We know that doing this for all items of a custom post type is possible by using the `et_builder_post_types` filter and passing the name of the CPT. 

But instead of that we'd like to **pass the IDs** of the posts for which we would like the builder to be activated.

Which filter can be used for that kind of operation?

#### Example of using the above filter
```
function et_pb_extend_supported_post_types( $post_types ) {
    $new_post_types = array( 'product' );

    return array_merge( $post_types, $new_post_types );
}
add_filter( 'et_builder_post_types', 'et_pb_extend_supported_post_types' );
```

**Comment by code-with-mehedi** [comment]
@cxlxin, You can try this hook and hope this will help you `et_builder_fb_enabled_for_post`

Let me know if you have any more questions.

Thanks
Mehedi

**Comment by cxlxin** [comment]
@code-with-mehedi,

I really appreciate your help though it doesn't work for me.

Thanks,
cxlxin
