### ISSUE TITLE
API link requires CAPTCHA

### ISSUE THREAD

**Issue by kuliebiakin** [elegantthemes/create-divi-extension#531]
### Problem Description

We are using Composer to install and update Divi on our sites through API link `https://www.elegantthemes.com/api/api_downloads.php?api_update=1&theme=Divi&api_key={%DIVI_API_KEY}&username={%DIVI_USERNAME}` but now it could ask to input CAPTCHA, so, it becomes not possible to use theme in CI/CD.

### Steps To Reproduce
Request API link with e.g. Curl: 
```
curl 'https://www.elegantthemes.com/api/api_downloads.php?api_update=1&theme=Divi&api_key={%DIVI_API_KEY}&username={%DIVI_USERNAME}'
```
It will return Cloudflare's HTML page with CAPTCHA form.

### Screenshot and/or gif
![Screenshot at Dec 14 19-28-55](https://user-images.githubusercontent.com/6066592/146049325-10e8aa6e-c300-45a7-9f97-00a8c3c53332.png)

**Comment by lanresmith** [comment]
Thanks for the request @kuliebiakin! I just want to first state that this isn't our originally intended or supported use of that API endpoint. However, out of curiosity, which CI are you using? How frequent is it running and did it ever work or has it thrown the captcha form the start? I would suspect that its getting blocked for the request potentially occurring too often.

**Comment by kuliebiakin** [comment]
Hello @lanresmith ,

Yep, I understand that it's not original use of endpoint however we are trying to find better way to handle updates than copying archive or theme itself into project after new Divi releases when using Composer with CI and this method was good before Captcha started to ask to pass security check.

We are using Jenkins and Captcha appears on every request and probably it's a proper behavior of it as request is not being made by a human.

**Comment by lanresmith** [comment]
Yeah @kuliebiakin, it's great you're innovating and trying this out! But yeah, looks like CloudFlare is stepping in and blocking your request, something we aren't able to prevent. With that, an alternative is you could manually update Divi or within WP interface, and commit the changes in your repo rather than trying to load it dynamically on the fly during CI.

**Comment by kuliebiakin** [comment]
Thanks, for your help.

Yeah, currently we are doing something similar by adding zip archive into project and using https://getcomposer.org/doc/05-repositories.md#package-2 to set path where to download.
