### ISSUE TITLE
Is it possible to get number of child modules in static css(props) of parent module(jsx)?

### ISSUE THREAD

**Issue by Lovely-Fellow** [elegantthemes/create-divi-extension#539]
### Problem Description
I need to add css using the value calculated by number of child modules in parent module.
I was able to get the number of child module in **render()** function using **this.props.content.length**.
But I can't generate css using this value in render function because there is no way to call **additionalCss.push** as in **static css(props)** function.

So I need one of following ways.
1. Generate css in **render()** function
2. Get number of child module in static **css(props)** function

### Steps To Reproduce
1.

**Comment by Lovely-Fellow** [comment]
I've got the idea from the answer of [other issue](https://github.com/elegantthemes/create-divi-extension/issues/90#issuecomment-396077548).
Here is code how I've implemented.

`customCss(props) {
  const additionalCss = [];
  const number_of_child_items = this.props.content.length;
  // Calculate variables using **number_of_child_items** 
	// Use same type of code as in static css(props)
  additionalCss.push([{
    selector: 'xxx',
    declaration: `prop:value`,
  }]);
  /* Generate style code from additionalCss*/
  additionalCss.forEach((element, index) => {
    additionalCss[index] = `
      ${element[0].selector.replace(
      '%%order_class%%', 
      `.${props.moduleInfo.orderClassName}`)}{
        ${element[0].declaration}
      }`;
  });
  return additionalCss.join('');
}
render() {
  return (
    <Fragment>
    <style>
        { this.customCss(this.props) }
      </style>
    </Fragment>
  )
}`

**Comment by renzocastillo** [comment]
@Lovely-Fellow  do you know how can I do this using php? I want to retrieve the quantity of child modules of current parent module

**Comment by MTaimoor79** [comment]
@Lovely-Fellow I am also facing the same problem as you faced. did you find any solution?
Thanks in advance

**Comment by Lovely-Fellow** [comment]
@renzocastillo Can't get the number of child modules of the current parent module static css() function.
But as we can get it in render() function using this.props.content.length, I've made customCss and called it from the render function to achieve my purpose.

**Comment by renzocastillo** [comment]
Thank you @Lovely-Fellow . I find it helpful for the frontend. Im struggling a little bit to get it at the backend
