### ISSUE TITLE
Can't get "npx create-divi-extension my-extension" to work

### ISSUE THREAD

**Issue by ekesto** [elegantthemes/create-divi-extension#611]
### Problem Description

Running `npx create-divi-extension my-extension` currently results in the following output:

```
Aborting installation.
Unexpected error. Please report it as a bug:
Error: Cannot find module '/Users/example/projects/divi-local-dev/app/public/wp-content/plugins/example-divi-extension/node_modules/divi-scripts/package.json'
Require stack:
- /Users/example/.npm/_npx/11760/lib/node_modules/create-divi-extension/createDiviExtension.js
- /Users/example/.npm/_npx/11760/lib/node_modules/create-divi-extension/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at checkNodeVersion (/Users/example/.npm/_npx/11760/lib/node_modules/create-divi-extension/createDiviExtension.js:552:23)
    at /Users/example/.npm/_npx/11760/lib/node_modules/create-divi-extension/createDiviExtension.js:340:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/example/.npm/_npx/11760/lib/node_modules/create-divi-extension/createDiviExtension.js',
    '/Users/example/.npm/_npx/11760/lib/node_modules/create-divi-extension/index.js'
  ]
}
```

### Steps To Reproduce

Local: v6.5.2
Node: v14.21.1
NPM: 6.14.17
Yarn (via NPM): 3.3.0

I tried the latest LTS version of Node (as described in the [How To Create A Divi Extension](https://www.elegantthemes.com/documentation/developers/create-divi-extension/) tutorial, but then I got the following error in a `pack.log`:

```
Packing grunt-po2mo@https://github.com/elegantthemes/grunt-po2mo.git#commit=26eca7c892db50837b58fdcf3771c5eb331a2ead from sources
Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile

➤ YN0000: Retrieving https://classic.yarnpkg.com/latest.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-1.22.19.cjs
➤ YN0000: Done in 1s 391ms

yarn install v1.22.19
[1/5] Validating package.json...
error grunt-po2mo@0.1.5: The engine "node" is incompatible with this module. Expected version "12.x || 14.x". Got "18.12.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I'm stuck. Really frustrating, as I'm really motivated to dive into the Divi Extension world :)

Appreciate any hint! What version work for you?

**Comment by ayubadiputra** [comment]
@ekesto Sorry for the late response and for the issue you experienced with.

Unfortunately, it only supports Node 14.x at this moment. Divi builder itself is still using Node 14.x as well as the other ET products like Extra theme and Bloom plugin. So, I will suggest you to use switch to Node 14.x on your project extension.

**Comment by ekesto** [comment]
@ayubadiputra, thanks for your feedback.

As noted in my post, I did change the versions to the following:

Local: v6.5.2
Node: v14.21.1
NPM: 6.14.17
Yarn (via NPM): 3.3.0

With this setup I get the error described in **Problem Description** above.. Any clue on what that could be?

**Comment by ayubadiputra** [comment]
We just fixed the incompatible Grunt and Node versions issue here [Package :: Update grunt-wp-i18n dependency to fix incompatible grunt and node version](https://github.com/elegantthemes/create-divi-extension/pull/626#top). It should work now. However, it's still require Node 14 (i.e. `14.17.0`) due to Divi Builder 4 still use Node 14 as well.

Here the video how the latest update works:

https://user-images.githubusercontent.com/9313128/229263392-c9b987fc-4b7d-46ad-80bc-1716fa910cfd.mp4
