### ISSUE TITLE
Node version problems. Once updated wants older version, once older, then requires newer

### ISSUE THREAD

**Issue by StenLeinasaar** [elegantthemes/create-divi-extension#625]
### Problem Description

Once I run the command npx create-divi-extension, it argues with me about the node version. I downloaded node manager and downgraded to LTS for version 14 and then it required a newer one. Once I reinstalled the newer one, it wanted the older one again.

Is it something I am doing wrong? Yarn and node are installed. I am using node manager. 

Operating system is MacOs Ventura 13.2.1
Graphics: Intel UHD Graphics 630
Processor 2.4 Ghz 8 core intel core i9 

Any tips or pointers would be helpful. 

### Steps To Reproduce
1. Run the command npx create-divi-extension my-extension
2. Update or downgrade node version as requested
3. Re-run step 1. 

### Screenshot and/or gif

Here are screenshots
<img width="963" alt="Screenshot 2023-03-24 at 11 46 39 AM" src="https://user-images.githubusercontent.com/83982253/227980828-fc8f28ef-c117-4617-a378-2a77707814f3.png">
<img width="531" alt="Screenshot 2023-03-24 at 11 45 47 AM" src="https://user-images.githubusercontent.com/83982253/227980872-9c9d27a6-14ca-4135-8b6a-25c4a88e3c32.png">
<img width="823" alt="Screenshot 2023-03-24 at 11 45 10 AM" src="https://user-images.githubusercontent.com/83982253/227980909-f4da5f11-2950-4f55-a955-50d9e5441dcc.png">

**Comment by ayubadiputra** [comment]
We just fixed the incompatible Grunt and Node versions issue here [Package :: Update grunt-wp-i18n dependency to fix incompatible grunt and node version](https://github.com/elegantthemes/create-divi-extension/pull/626#top). It should work now. However, it's still require Node 14 (i.e. `14.17.0`) due to Divi Builder 4 still use Node 14 as well.

**Comment by StenLeinasaar** [comment]
Works. Thank you!

**Comment by StenLeinasaar** [comment]
Did the update cause any problems with rendering? My custom element is not showing up after following the elegant themes tutorial 1 to 1
