### ISSUE TITLE
Woocommerce Dynamic data (this product) in custom module

### ISSUE THREAD

**Issue by sebalaini** [elegantthemes/create-divi-extension#632]
### Problem Description
I'm new to building custom modules and I'm following this [tutorial](https://www.elegantthemes.com/documentation/developers/divi-module/how-to-create-a-divi-builder-module/) to create a new Divi module as we want to use woocommerce for our project but the woo modules aren't fit 100% to our needs, is there a guide or something that specify how to get the product data and insert it into the module I'm creating?

The product in question would have custom attributes so some existing modules are OK, but I'd need to create some of them and I need to access the data coming from the DB.

### Steps To Reproduce
this is my PHP code
```
<?php

class wsdm_Stars extends ET_Builder_Module
{

    public $slug       = 'wsdm_woo_stars';
    public $vb_support = 'on';

    public function init()
    {
        $this->name = esc_html__('Woocommerce Stars', 'wsdm-woo-stars');
    }

    public function get_fields()
    {
        return array(
            'heading'     => array(
                'label'           => et_builder_i18n('Heading'),
                'type'            => 'text',
                'option_category' => 'basic_option',
                'description'     => esc_html__('Input your desired heading here.', 'wsdm-woo-stars'),
                'toggle_slug'     => 'main_content',
                'dynamic_content' => 'text',
            ),
        );
    }

    public function render($attrs, $content = null, $render_slug)
    {
        return sprintf(
            '<h1 class="simp-simple-header-heading">%1$s</h1>',
            esc_html($this->props['heading']),
        );
    }
}

new wsdm_Stars;
```

For this particular module, I need only the `estrellas` attribute, but Ideally I'd like to get all of the attributes directly in PHP or JS and then format them directly without need to select the dynamic data in the Divi module on the website.

### Screenshot and/or gif
just for testing purposes, I managed to get the product title as it's a standard field but the render isn't what I was expecting
![image](https://user-images.githubusercontent.com/17096352/235912573-b7fb9480-5272-42a4-9234-c567959581e4.png)

this is the data I want to access, the `estrellas` attribute
![image](https://user-images.githubusercontent.com/17096352/235912962-bcc98e98-a17d-4f65-8598-ada58ec2d375.png)

**Comment by sebalaini** [comment]
I'm gonna close the issue as I found out how to do it after hours spent on reverse engineering

**Comment by arobbins** [comment]
@sebalaini Do you remember what your solution was? Running into the same thing ...

**Comment by sebalaini** [comment]
🤔 no, but if you want to check my code I opened the repo and archived it as I don't work anymore on that project.
I hope it helps you https://github.com/sebalaini/divi_custom_modules_for_reviews_website
