### ISSUE TITLE
"et_module_shortcode_output" Filter causes Divi Timeout error in the visual builder

### ISSUE THREAD

**Issue by munirkamal** [elegantthemes/create-divi-extension#75]
### Problem Description
I am working on a Divi extension, where I am trying to manipulate the Divi Section output. The issue I am facing is that the filter "et_module_shortcode_output" is causing the Divi Timeout error even though I am just inserting a small string "test". 

### Here is my code
     add_filter( 'et_module_shortcode_output', 'render_section', 10, 3 );
     
    function render_section($output, $render_slug, $module){
	if('et_pb_section' !== $render_slug) return $output;
	$output .= 'test';
	return $output;
     } 

### Screenshot of the error I am getting
![image 2018-05-24 at 4 12 48 pm](https://user-images.githubusercontent.com/5817882/40482627-e1860864-5f6e-11e8-94d3-da60fa4b598e.png)

Looking forward for some help fixing this issue.

TIA,
Munir

**Comment by dangub86** [comment]
I do not know why it does this ... working with the modules there are no problems and even using 'et_pb_row' everything works correctly ... only for the sections it does not work :( Maybe we have to wait for a next update?

**Comment by munirkamal** [comment]
@dangub86 

Yes, you are right, it is working with rows but then in the visual builder it is making row settings not editable and also all the content within row doesn't appear.

**Comment by jocastaneda** [comment]
The reason is because the `output` is different on the Visual Builder. If you look at the the `class-et-builder-element` file and just above the filter, you will see 

```php
<?php // around line 1575
$render_method = $et_fb_processing_shortcode_object ? 'render_as_builder_data' : 'render';
$output        = $this->{$render_method}( $attrs, $content, $render_slug, $parent_address, $global_parent, $global_parent_type );
```

When it is on the VB, the method used is the `render_as_builder_data` which returns an array. It is something like:

```php
<?php // around line 2030
$object = array(
	'_i'                          => $_i,
	'_order'                      => $_i,
	// TODO make address be _address, its conflicting with 'address' prop in map module... (not sure how though, they are in diffent places...)
	'address'                     => $address,
	'child_slug'                  => $this->child_slug,
	'vb_support'                  => $this->vb_support,
	'parent_address'              => $parent_address,
	'shortcode_index'             => $render_count,
	'type'                        => $render_slug,
	'component_path'              => $component_path,
	'main_css_element'            => $this->main_css_element,
	'attrs'                       => $attrs,
	'content'                     => $prepared_content,
	'is_module_child'             => 'child' === $module_type,
	'is_official_module'          => $this->_is_official_module,
	'child_title_var'             => $child_title_var,
	'child_title_fallback_var'    => $child_title_fallback_var,
	'advanced_setting_title_text' => $advanced_setting_title_text,
	'wrapper_settings'            => $this->get_wrapper_settings( $render_slug ),
);
```

The important part is the `content` key. You could potentially use an `is_array()` check. I'm trying to remember the correct way of handling that because it sort of does the outer shortcode then internal when generating that object.

You could get a better idea as well if you use something like:

```php
<?php // log the data so we can see what to modify
 add_filter( 'et_module_shortcode_output', function( $output, $slug, $object ) {
  if ( is_array( $output ) ) {
    // we are in the VB
    // log what the data is.
    error_log( print_r( $output, true ) );
    return $output;
  }
  return $output
}, 10, 3 );
```

**Comment by munirkamal** [comment]
@jocastaneda 

Thank you for the response, I just saved a log as you mentioned. Would you please help me fixing my code to work with Visual Builder.

Attached is the log file. Let me know if you need anything else.
[error.log](https://github.com/elegantthemes/create-divi-extension/files/2039091/error.log)

TIA,
Munir

**Comment by lots0logs** [comment]
Hi @munirkamal , has this issue been resolved yet?

**Comment by munirkamal** [comment]
Hi @lots0logs , Yes it is.
