### ISSUE TITLE
Where are the module credits shown?

### ISSUE THREAD

**Issue by xxtesaxx** [elegantthemes/create-divi-extension#8]
I'm looking around for quiet a while now but I cant find where the $module_credits are used. Can you please clarify? 😁

**Comment by xxtesaxx** [comment]
Hmm I think I am blind :(  
![modal](https://user-images.githubusercontent.com/3000808/39074637-80ad4980-44f2-11e8-9ecb-5c3df7731037.PNG)

**Comment by lots0logs** [comment]
Is this a new custom module or an existing one? Do you have `$vb_support` set to `on` in your PHP class?

**Comment by lots0logs** [comment]
(module credits are only shown for modules that have full support for the Visual Builder)

**Comment by xxtesaxx** [comment]
It's a new custom module and it's using
`public $vb_support = 'on';
	protected $module_credits = array(
		'module_uri' => 'https://divi-sensei.com/plugin',
		'author'     => 'Divi Sensei',
		'author_uri' => 'https://divi-sensei.com',
	);`

**Comment by lots0logs** [comment]
Looks like you found a bug. I'll make sure we get it fixed in the next update.

**Comment by SatishKumarPrajapati** [comment]
Hello, Module credit bug fixed but now showing only in child item not on all modules.
