### ISSUE TITLE
frontend.js and how does it work?

### ISSUE THREAD

**Issue by mrkenng** [elegantthemes/create-divi-extension#9]
I editing the file frontend.js with 

```
// This script is loaded both on the frontend page and in the Visual Builder.

jQuery(function($) {
	$('.simp_simple_header').css('background','black');
});
```

And it is working only on frontend page. Not the Visual Builder. 
Is this related to the https://www.elegantthemes.com/documentation/developers/code-reference/divi-builder-javascript-api/ ?

Also, do you have an example on how this will work on the visual builder?

**Comment by lots0logs** [comment]
It should work in the builder as well so long as you updated your extension class with the changes to the method I provided here: https://github.com/elegantthemes/create-divi-extension/issues/5#issuecomment-383213326

That being said, one important thing you have to understand about React Components is that React must be in complete control of their rendering. If you modify the dom elements from outside your component (like in the example code you provided) it can and in most cases will cause errors in React. Here's an example of how to add inline css styles to your react component on-the-fly:

https://github.com/elegantthemes/divi-extension-example/blob/8837a49901b81c410fdad56f067c0523250d0e8e/includes/modules/CustomCtaAllOptions/CustomCtaAllOptions.jsx#L9-L53
