### ISSUE TITLE
Parent :: static css(props) :: get the module passed in / Child :: get the default values

### ISSUE THREAD

**Issue by jcdotnet** [elegantthemes/create-divi-extension#90]
### Problem Description
Hello everyone, I need to get the module order (1,2,3,..) inside the static css method since we don't have access to `props.moduleInfo.order` like we have in the class instance. Some props are missing there.

Is there a easy way to get the value? Can we process the `%%order_class%%` string or something? Does the JavaScript API help us here?

If not possible, is there an easy way to get the content? 

Speaking of missing props, some props that store the default values that we defined in the module are missing too and we need to wait to a re-render to access them. For example, if we set a default value for the field circle_background_color, the prop should be added to the React component via this.props.circle_background_color. Same happens with the advanced fields.

Thank you.

### Steps To Reproduce
1. We can get the module order class via props  
2. We have a static method that allow us to add CSS by adding the styles to the additionalCss array.
3. This static method receives some props.
4. The prop that gives us the module order hasn't been added to those props.
5. The module order needs to be stored in a variable.

### Screenshot and/or gif
 ```
static css(props) {
       console.log(props.moduleInfo) // undefined!! 
```

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [x] Helpful title used
- [x] Detailed description
- [x] Steps to reproduce included
- [ ] Support Ticket URL included
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Steps to reproduce proven solved
- [ ] Test included and coverage acceptable and all Tests passing?
- [ ] PR description has layman's description of problem and solution and "Areas Affected" listed/explained?
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Estimated points on issue
- [ ] Proper code documentation and conventions?
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Peer Review</strong>
- [ ] PR branch includes latest commits from master branch (at the time of checking)?
- [ ] Steps to reproduce proven solved
- [ ] Affected areas are tested and ok
- [ ] Proper code documentation and conventions
- [ ] Proper RTL appearance
- [ ] i18n used if applicable
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated?

<strong>Quality Assurance</strong>
- [ ] All tests passed on CircleCI.
- [ ] Steps to reproduce passed, the fix works.
- [ ] No errors in console or output 
- [ ] Affected areas are tested and ok
- [ ] The fix does not change a customer's website in any surprising or unintended way
  - [ ] If Divi's design <em>is</em> adjusted, settings are migrated gracefully and invisibly

<strong>Design Review</strong>
- [ ] UI is to spec
- [ ] UX is to spec
- [ ] Design is to spec
- [ ] No surprising visual changes to a customer's website will be experienced after updating
  - [ ] Any/all visual changes are migrated gracefully

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used? Nonce used? Perms checked? All user input sanitized and validated? Intentional unsanitized/unescaped functions used?
- [ ] Database saved/updated? Data sanitized and validated?
- [ ] Variable output properly escaped and validated? 
- [ ] i18n used if applicable
- [ ] Implementation acceptable, DRY, Scaleable, future safe
- [ ] Best practices used, cleverness and grokage, ES6 use, etc.

**Comment by jcdotnet** [comment]
Finally I solved the issue by using callback refs and keeping track of my modules with static fields. But I'm still not getting the props with default values.

**Comment by jcdotnet** [comment]
Finally I am getting the default values, it's not a bug, we just need a better support from ET, the official documentation covers only the basics. It's like a documentation for designers who want to develop very simple custom modules, not for actual developers.

I left this open in case someone knows how to get the module order in the static CSS method, thank you in advance.

**Comment by BoDonkey** [comment]
I'm still having a problem with needing to re-render in order to get the defaults - how did you remedy this @jcdotnet?

**Comment by jcdotnet** [comment]
@BoDonkey the default values are not passed to the CHILD component, if you are not using items just check the documentation and play around (add the default parameter to the field, check if the field depends on another field, etc), if not I'm afraid you will need a workaround like this:

`const fieldWithDefault = props.field_with_default ? props.field_with_default : 'off'; // workaround to get the default value if hasn't been passsed to the component yet `

Sorry I can't help, I tested only in the parent, hope ET gives us support here.

**Comment by xxtesaxx** [comment]
Hmm I most get the default values in `static css(props)` I believe and then use %%order_class%% in the css to apply them. I only found some very rare instances of settings from the advanced fields where defaults were not applied but I cant remember which ones. 

One thing I noted though is that if you try to separate multiple selectors using commas like in php, it breaks the whole css so you have to create a lot more instances of styles than in php:

static css(props) {
        const additionalCss = [];

        additionalCss.push([{
            selector: '%%order_class%% .text_desktop',
            declaration: 'display: block;',
        }]);

        additionalCss.push([{
            selector: '%%order_class%% .text_desktop',
            declaration: 'display: none;',
            device: 'tablet',
        }]);

        additionalCss.push([{
            selector: '%%order_class%% .text_desktop',
            declaration: 'display: none;',
            device: 'phone',
        }]);

        additionalCss.push([{
            selector: '%%order_class%% .text_tablet',
            declaration: 'display: none;',
        }]);

        additionalCss.push([{
            selector: '%%order_class%% .text_tablet',
            declaration: 'display: block;',
            device: 'tablet',
        }]);

        additionalCss.push([{
            selector: '%%order_class%% .text_tablet',
            declaration: 'display: none;',
            device: 'phone',
        }]);

        additionalCss.push([{
            selector: '%%order_class%% .text_phone',
            declaration: 'display: none;',
        }]);

        additionalCss.push([{
            selector: '%%order_class%% .text_phone',
            declaration: 'display: none;',
            device: 'tablet',
        }]);

        additionalCss.push([{
            selector: '%%order_class%% .text_phone',
            declaration: 'display: block;',
            device: 'phone',
        }]);

        return additionalCss;
    }

**Comment by jcdotnet** [comment]
The %%order_class%% is processed when the CSS is rendered, I would like to use the value in the static method.

You are getting the props with default values in the main (parent) module, right? Default values are removed from props for child modules. See #48

About the CSS you can separate the selector by commas, you can even push more than one object at one time:

 ```
additionalCss.push([{
        selector: '%%order_class%% .text_desktop',
        declaration: 'display: block;',
}, {
       selector: '%%order_class%% .text_desktop',
       declaration: 'display: none;',
       device: 'tablet',
}, {
      selector: '%%order_class%% .text_desktop',
      declaration: 'display: none;',
      device: 'phone',
}]);
```

**Comment by xxtesaxx** [comment]
Yeah of course. I meant that in php you can separate selectors like "selector" => "%%order_class%% .some, %%order_class%% .other" which does not work in JS. There you have to create one object for each selector. :) 

Have you tried setting the option `"default_on_child" => true,` in the child settings?

**Comment by jcdotnet** [comment]
Thank you @xxtesaxx  and @lots0logs , `"default_on_child" => true` does the trick.

About the selectors this work for me:
`selector:    '%%order_class%% .text1, %%order_class%% .text2',
`
Are you including JS variables? If so check their values are correct. If not, you can go to the HTML and see the output, you can find those styles in a div element at the end of your module rendering.

**Comment by jcdotnet** [comment]
Anyone can help on getting the order module inside the css static method? I mean, that's a static method and the only info that we have about the module is the props that are passed in, but the moduleInfo value is missing and the other ones are shared: there can be several modules with those values! 

I want to keep track of the modules passed to that static method since I can have multiple modules. I need to interate over the module items and I can't do it correctly if I don't know which module is passed. My workarounds don't work so far, I end up iterating over other module items. 

I have this static array: 
[ {'moduleOrder': 1, 'items': [...]}, {'moduleOrder': 2, 'items: [...], ...] that's why i need to know the module order.

How can I keep track of my modules? Any help? There has to be a straightforward way to do this. Thank you in advance.

**Comment by xxtesaxx** [comment]
Why do you need the number in `static css(props)`? Simply use %%order_class%% in the child modules React components `static css(props)` or inline the styles in `render()` (either in the parent or the child). Thats probably safer than fiddling with numbers which then do not properly work in the php equivalent.

Alternatively simply add your own classes to each child in `render()` and then use those classes to target the selector. Also keep in mind that while in React you have a "order", the number from this order is only the number of the module in its parent. You can check that by having your module in multiple columns of a multi-column-row and then copy the row multiple times in the same section and then copy the section as well. You'll see that the numbers are repeatet so thats no good way to target CSS. 

Always use the %%order_class%% selector to target something in the current module. Unlike the order, the order_class is replaced by the correct selector which is unique across multiple columns, rows and sections.

But maybe I just don't understand what you are trying to acomplish and I would appreciate it if you could explain in detail what you are trying to do. :)

**Comment by jcdotnet** [comment]
I need to iterate over the module items to do some calculations. I already use the `%%order_class%%` for the CSS (I place here the results of those calculations) but need to know which module is passed to `static css(props)`. 

This "order" that you comment and I can get in the render() method is the order I want to get in the `static css(props)` since I have stored the items for every module using that module order as the key. 

The module order is the way I think it's easier, there can be easier ways to keep track of the modules. I don't know.  

I have noticed (I'm only testing but this can help) that the static css might follow this workflow:
- MyModule with order 2 is rendered and then another MyModule with order 4 is rendered.
Once rendered the static method is called to form the styles, but in the reverse order, first is passed the MyModule with order 4 and then MyModule with order 2.  It might follow a LIFO behavior. But again, just testing.

It would be very useful if we can have a look to the official modules implementation, especially the Slider component which might be the closest one to the module I want to develop. 

It's really weird that I'm the only one interested in this, maybe I am on the wrong direction.

**Comment by jcdotnet** [comment]
Yeah, you are right @xxtesaxx but my css is quite complex and I think I will do something like that;

 ```
customCss(props, css) {
   css.push([
      `.main .selector1, .main .selector2  {font-size: ${fontSize}px;}`    
   ]);
    
    if ('off' === props.useWhatever) {
      css.push([
       '.main .selector {font-size: 32px}'
      ]);
    }
    if ('on' === props.useWhatever) {
      css.push([
        `.main .selector { font-size: ${ fontSizeOfWhatever }px}`,
      ]);
    }
}
```
and then:

```
render() {
    let additionalCss = [];
    this.customCss(this.props, additionalCss);
    
    return (  
      <Fragment>
          <div class="main">
                ...
                { this.props.content }
		...		
          </div>
          <style>
                {additionalCss.join('')}
          </style>         
     </Fragment>
    );
} 
```
The downside is that I will not able to use the selector, declaration, media and so on.  But we really don't need to and this way we can get rid of the static css method.

**Comment by jcdotnet** [comment]
I'm reopening this issue because the styles I added in `render()` are not being applied in the custom views (tablet and phone). 

After looking into that issue I have noticed that some classes are added when the views are active:

```
.et_fb_preview_active.et_fb_preview_active--responsive_preview 
.et_fb_preview_active.et_fb_preview_active--responsive_preview.et_fb_preview_active--responsive_preview--phone_preview
```

So in order for my custom styles to be applied to the builder views I have to add this classes as a workaround:

```
.et_fb_preview_active.et_fb_preview_active--responsive_preview.et_fb_preview_active--responsive_preview--tablet_preview .mySelector {
   font-size: 30px; // tablet
}
.et_fb_preview_active.et_fb_preview_active--responsive_preview.et_fb_preview_active--responsive_preview--phone_preview .mySelector {
   font-size: 15px; // phone
}

```
This is how it is done behind the scenes, isn't it? Do you recommend that I do that? If not, there is a better way to achieve this without using the `static css(props)` method?

Ideally I would call a function that gives me these classes names (in case they change in later versions), is there any functions or something I can use to get the classes and then prefix them to mine?

Thank you!
