### ISSUE TITLE
Custom Module repeating fields

### ISSUE THREAD

**Issue by antonkor** [elegantthemes/create-divi-extension#96]
Is there documentation on how to create fields that can be repeatable. Mainly the "add new slide" feature. https://cl.ly/0p3H1N3U421R

What i would like to build is a basic touch enabled slider since the default slider only has the fading transitions.

a example like the default hello world (php and jsx) would be sure nice.

**Comment by motylo** [comment]
Only by creating child_slug object.
Check in CustomCtaChild in https://github.com/elegantthemes/divi-extension-example/tree/master/includes/modules/CustomCtaChild

So, you create main element like antonkorSlider with full config and antonkorSliderSlug with repeatable fields (suppose: background, text, photo etc.).

**Comment by BoDonkey** [comment]
Each of those "repeatable fields" are child items. So, for the slider there are two linked files, the slider.php file and the slideritem.php file. In the [Divi Extension Example on GitHub](https://github.com/elegantthemes/divi-extension-example) you can follow the example of the CustomCtaParent and CustomCtaChild modules to create a new slider.

**Comment by xxtesaxx** [comment]
It would be great to have repeater fields though. For example in Elementor you can have more than one repeater per module which is really awesome. Multiple childs per module would be great addition to Divi as well

**Comment by antonkor** [comment]
Thanks guys.

I got the example module working by also including the parent module CustomCtaParent. I guess i can reverse engineer things from here.
